// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package attestation

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAttestationVerifierInterface creates a new instance of MockAttestationVerifierInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttestationVerifierInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttestationVerifierInterface {
	mock := &MockAttestationVerifierInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttestationVerifierInterface is an autogenerated mock type for the AttestationVerifierInterface type
type MockAttestationVerifierInterface struct {
	mock.Mock
}

type MockAttestationVerifierInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttestationVerifierInterface) EXPECT() *MockAttestationVerifierInterface_Expecter {
	return &MockAttestationVerifierInterface_Expecter{mock: &_m.Mock}
}

// VerifyAttestation provides a mock function for the type MockAttestationVerifierInterface
func (_mock *MockAttestationVerifierInterface) VerifyAttestation(ctx context.Context, tokenString string, provider AttestationProvider) (*AttestationClaims, error) {
	ret := _mock.Called(ctx, tokenString, provider)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAttestation")
	}

	var r0 *AttestationClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, AttestationProvider) (*AttestationClaims, error)); ok {
		return returnFunc(ctx, tokenString, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, AttestationProvider) *AttestationClaims); ok {
		r0 = returnFunc(ctx, tokenString, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AttestationClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, AttestationProvider) error); ok {
		r1 = returnFunc(ctx, tokenString, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestationVerifierInterface_VerifyAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAttestation'
type MockAttestationVerifierInterface_VerifyAttestation_Call struct {
	*mock.Call
}

// VerifyAttestation is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
//   - provider AttestationProvider
func (_e *MockAttestationVerifierInterface_Expecter) VerifyAttestation(ctx interface{}, tokenString interface{}, provider interface{}) *MockAttestationVerifierInterface_VerifyAttestation_Call {
	return &MockAttestationVerifierInterface_VerifyAttestation_Call{Call: _e.mock.On("VerifyAttestation", ctx, tokenString, provider)}
}

func (_c *MockAttestationVerifierInterface_VerifyAttestation_Call) Run(run func(ctx context.Context, tokenString string, provider AttestationProvider)) *MockAttestationVerifierInterface_VerifyAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 AttestationProvider
		if args[2] != nil {
			arg2 = args[2].(AttestationProvider)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAttestationVerifierInterface_VerifyAttestation_Call) Return(attestationClaims *AttestationClaims, err error) *MockAttestationVerifierInterface_VerifyAttestation_Call {
	_c.Call.Return(attestationClaims, err)
	return _c
}

func (_c *MockAttestationVerifierInterface_VerifyAttestation_Call) RunAndReturn(run func(ctx context.Context, tokenString string, provider AttestationProvider) (*AttestationClaims, error)) *MockAttestationVerifierInterface_VerifyAttestation_Call {
	_c.Call.Return(run)
	return _c
}
