// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package attestation

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBoundAttestationEvidenceVerifier creates a new instance of MockBoundAttestationEvidenceVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoundAttestationEvidenceVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoundAttestationEvidenceVerifier {
	mock := &MockBoundAttestationEvidenceVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoundAttestationEvidenceVerifier is an autogenerated mock type for the BoundAttestationEvidenceVerifier type
type MockBoundAttestationEvidenceVerifier struct {
	mock.Mock
}

type MockBoundAttestationEvidenceVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoundAttestationEvidenceVerifier) EXPECT() *MockBoundAttestationEvidenceVerifier_Expecter {
	return &MockBoundAttestationEvidenceVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockBoundAttestationEvidenceVerifier
func (_mock *MockBoundAttestationEvidenceVerifier) Verify(ctx context.Context, attestationBytes []byte, challenge []byte) (*VerifiedAttestation, error) {
	ret := _mock.Called(ctx, attestationBytes, challenge)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *VerifiedAttestation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) (*VerifiedAttestation, error)); ok {
		return returnFunc(ctx, attestationBytes, challenge)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) *VerifiedAttestation); ok {
		r0 = returnFunc(ctx, attestationBytes, challenge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifiedAttestation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, []byte) error); ok {
		r1 = returnFunc(ctx, attestationBytes, challenge)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoundAttestationEvidenceVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockBoundAttestationEvidenceVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - attestationBytes []byte
//   - challenge []byte
func (_e *MockBoundAttestationEvidenceVerifier_Expecter) Verify(ctx interface{}, attestationBytes interface{}, challenge interface{}) *MockBoundAttestationEvidenceVerifier_Verify_Call {
	return &MockBoundAttestationEvidenceVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, attestationBytes, challenge)}
}

func (_c *MockBoundAttestationEvidenceVerifier_Verify_Call) Run(run func(ctx context.Context, attestationBytes []byte, challenge []byte)) *MockBoundAttestationEvidenceVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoundAttestationEvidenceVerifier_Verify_Call) Return(verifiedAttestation *VerifiedAttestation, err error) *MockBoundAttestationEvidenceVerifier_Verify_Call {
	_c.Call.Return(verifiedAttestation, err)
	return _c
}

func (_c *MockBoundAttestationEvidenceVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, attestationBytes []byte, challenge []byte) (*VerifiedAttestation, error)) *MockBoundAttestationEvidenceVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
