// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package attestation

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// VerifyAttestation provides a mock function for the type MockVerifier
func (_mock *MockVerifier) VerifyAttestation(attestation []byte) (*types.AttestationClaims, error) {
	ret := _mock.Called(attestation)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAttestation")
	}

	var r0 *types.AttestationClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*types.AttestationClaims, error)); ok {
		return returnFunc(attestation)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *types.AttestationClaims); ok {
		r0 = returnFunc(attestation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AttestationClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(attestation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_VerifyAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAttestation'
type MockVerifier_VerifyAttestation_Call struct {
	*mock.Call
}

// VerifyAttestation is a helper method to define mock.On call
//   - attestation []byte
func (_e *MockVerifier_Expecter) VerifyAttestation(attestation interface{}) *MockVerifier_VerifyAttestation_Call {
	return &MockVerifier_VerifyAttestation_Call{Call: _e.mock.On("VerifyAttestation", attestation)}
}

func (_c *MockVerifier_VerifyAttestation_Call) Run(run func(attestation []byte)) *MockVerifier_VerifyAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVerifier_VerifyAttestation_Call) Return(attestationClaims *types.AttestationClaims, err error) *MockVerifier_VerifyAttestation_Call {
	_c.Call.Return(attestationClaims, err)
	return _c
}

func (_c *MockVerifier_VerifyAttestation_Call) RunAndReturn(run func(attestation []byte) (*types.AttestationClaims, error)) *MockVerifier_VerifyAttestation_Call {
	_c.Call.Return(run)
	return _c
}
