// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package attestation

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttestationMethod creates a new instance of MockAttestationMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttestationMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttestationMethod {
	mock := &MockAttestationMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttestationMethod is an autogenerated mock type for the AttestationMethod type
type MockAttestationMethod struct {
	mock.Mock
}

type MockAttestationMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttestationMethod) EXPECT() *MockAttestationMethod_Expecter {
	return &MockAttestationMethod_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockAttestationMethod
func (_mock *MockAttestationMethod) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAttestationMethod_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockAttestationMethod_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockAttestationMethod_Expecter) Name() *MockAttestationMethod_Name_Call {
	return &MockAttestationMethod_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockAttestationMethod_Name_Call) Run(run func()) *MockAttestationMethod_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestationMethod_Name_Call) Return(s string) *MockAttestationMethod_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAttestationMethod_Name_Call) RunAndReturn(run func() string) *MockAttestationMethod_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAttestationMethod
func (_mock *MockAttestationMethod) Verify(request *AttestationRequest) (*types.AttestationClaims, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *types.AttestationClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*AttestationRequest) (*types.AttestationClaims, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*AttestationRequest) *types.AttestationClaims); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AttestationClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*AttestationRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestationMethod_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAttestationMethod_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - request *AttestationRequest
func (_e *MockAttestationMethod_Expecter) Verify(request interface{}) *MockAttestationMethod_Verify_Call {
	return &MockAttestationMethod_Verify_Call{Call: _e.mock.On("Verify", request)}
}

func (_c *MockAttestationMethod_Verify_Call) Run(run func(request *AttestationRequest)) *MockAttestationMethod_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *AttestationRequest
		if args[0] != nil {
			arg0 = args[0].(*AttestationRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAttestationMethod_Verify_Call) Return(attestationClaims *types.AttestationClaims, err error) *MockAttestationMethod_Verify_Call {
	_c.Call.Return(attestationClaims, err)
	return _c
}

func (_c *MockAttestationMethod_Verify_Call) RunAndReturn(run func(request *AttestationRequest) (*types.AttestationClaims, error)) *MockAttestationMethod_Verify_Call {
	_c.Call.Return(run)
	return _c
}
