// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kmsClient

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/peering"
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	"github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKMSClient creates a new instance of MockKMSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMSClient {
	mock := &MockKMSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKMSClient is an autogenerated mock type for the KMSClient type
type MockKMSClient struct {
	mock.Mock
}

type MockKMSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMSClient) EXPECT() *MockKMSClient_Expecter {
	return &MockKMSClient_Expecter{mock: &_m.Mock}
}

// CollectPartialSignatures provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) CollectPartialSignatures(appID string, operators *peering.OperatorSetPeers, threshold int) (map[common.Address]types.G1Point, error) {
	ret := _mock.Called(appID, operators, threshold)

	if len(ret) == 0 {
		panic("no return value specified for CollectPartialSignatures")
	}

	var r0 map[common.Address]types.G1Point
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *peering.OperatorSetPeers, int) (map[common.Address]types.G1Point, error)); ok {
		return returnFunc(appID, operators, threshold)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *peering.OperatorSetPeers, int) map[common.Address]types.G1Point); ok {
		r0 = returnFunc(appID, operators, threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.Address]types.G1Point)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *peering.OperatorSetPeers, int) error); ok {
		r1 = returnFunc(appID, operators, threshold)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_CollectPartialSignatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectPartialSignatures'
type MockKMSClient_CollectPartialSignatures_Call struct {
	*mock.Call
}

// CollectPartialSignatures is a helper method to define mock.On call
//   - appID string
//   - operators *peering.OperatorSetPeers
//   - threshold int
func (_e *MockKMSClient_Expecter) CollectPartialSignatures(appID interface{}, operators interface{}, threshold interface{}) *MockKMSClient_CollectPartialSignatures_Call {
	return &MockKMSClient_CollectPartialSignatures_Call{Call: _e.mock.On("CollectPartialSignatures", appID, operators, threshold)}
}

func (_c *MockKMSClient_CollectPartialSignatures_Call) Run(run func(appID string, operators *peering.OperatorSetPeers, threshold int)) *MockKMSClient_CollectPartialSignatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *peering.OperatorSetPeers
		if args[1] != nil {
			arg1 = args[1].(*peering.OperatorSetPeers)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_CollectPartialSignatures_Call) Return(addressToG1Point map[common.Address]types.G1Point, err error) *MockKMSClient_CollectPartialSignatures_Call {
	_c.Call.Return(addressToG1Point, err)
	return _c
}

func (_c *MockKMSClient_CollectPartialSignatures_Call) RunAndReturn(run func(appID string, operators *peering.OperatorSetPeers, threshold int) (map[common.Address]types.G1Point, error)) *MockKMSClient_CollectPartialSignatures_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) Decrypt(appID string, encryptedData []byte, operators *peering.OperatorSetPeers, threshold int) ([]byte, error) {
	ret := _mock.Called(appID, encryptedData, operators, threshold)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, *peering.OperatorSetPeers, int) ([]byte, error)); ok {
		return returnFunc(appID, encryptedData, operators, threshold)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, *peering.OperatorSetPeers, int) []byte); ok {
		r0 = returnFunc(appID, encryptedData, operators, threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, *peering.OperatorSetPeers, int) error); ok {
		r1 = returnFunc(appID, encryptedData, operators, threshold)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockKMSClient_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - appID string
//   - encryptedData []byte
//   - operators *peering.OperatorSetPeers
//   - threshold int
func (_e *MockKMSClient_Expecter) Decrypt(appID interface{}, encryptedData interface{}, operators interface{}, threshold interface{}) *MockKMSClient_Decrypt_Call {
	return &MockKMSClient_Decrypt_Call{Call: _e.mock.On("Decrypt", appID, encryptedData, operators, threshold)}
}

func (_c *MockKMSClient_Decrypt_Call) Run(run func(appID string, encryptedData []byte, operators *peering.OperatorSetPeers, threshold int)) *MockKMSClient_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *peering.OperatorSetPeers
		if args[2] != nil {
			arg2 = args[2].(*peering.OperatorSetPeers)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKMSClient_Decrypt_Call) Return(bytes []byte, err error) *MockKMSClient_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_Decrypt_Call) RunAndReturn(run func(appID string, encryptedData []byte, operators *peering.OperatorSetPeers, threshold int) ([]byte, error)) *MockKMSClient_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptForApp provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) DecryptForApp(appID string, ciphertext []byte, attestationTime int64) ([]byte, error) {
	ret := _mock.Called(appID, ciphertext, attestationTime)

	if len(ret) == 0 {
		panic("no return value specified for DecryptForApp")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, int64) ([]byte, error)); ok {
		return returnFunc(appID, ciphertext, attestationTime)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, int64) []byte); ok {
		r0 = returnFunc(appID, ciphertext, attestationTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, int64) error); ok {
		r1 = returnFunc(appID, ciphertext, attestationTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_DecryptForApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptForApp'
type MockKMSClient_DecryptForApp_Call struct {
	*mock.Call
}

// DecryptForApp is a helper method to define mock.On call
//   - appID string
//   - ciphertext []byte
//   - attestationTime int64
func (_e *MockKMSClient_Expecter) DecryptForApp(appID interface{}, ciphertext interface{}, attestationTime interface{}) *MockKMSClient_DecryptForApp_Call {
	return &MockKMSClient_DecryptForApp_Call{Call: _e.mock.On("DecryptForApp", appID, ciphertext, attestationTime)}
}

func (_c *MockKMSClient_DecryptForApp_Call) Run(run func(appID string, ciphertext []byte, attestationTime int64)) *MockKMSClient_DecryptForApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_DecryptForApp_Call) Return(bytes []byte, err error) *MockKMSClient_DecryptForApp_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_DecryptForApp_Call) RunAndReturn(run func(appID string, ciphertext []byte, attestationTime int64) ([]byte, error)) *MockKMSClient_DecryptForApp_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) Encrypt(appID string, data []byte, operators *peering.OperatorSetPeers) ([]byte, error) {
	ret := _mock.Called(appID, data, operators)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, *peering.OperatorSetPeers) ([]byte, error)); ok {
		return returnFunc(appID, data, operators)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, *peering.OperatorSetPeers) []byte); ok {
		r0 = returnFunc(appID, data, operators)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, *peering.OperatorSetPeers) error); ok {
		r1 = returnFunc(appID, data, operators)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockKMSClient_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - appID string
//   - data []byte
//   - operators *peering.OperatorSetPeers
func (_e *MockKMSClient_Expecter) Encrypt(appID interface{}, data interface{}, operators interface{}) *MockKMSClient_Encrypt_Call {
	return &MockKMSClient_Encrypt_Call{Call: _e.mock.On("Encrypt", appID, data, operators)}
}

func (_c *MockKMSClient_Encrypt_Call) Run(run func(appID string, data []byte, operators *peering.OperatorSetPeers)) *MockKMSClient_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *peering.OperatorSetPeers
		if args[2] != nil {
			arg2 = args[2].(*peering.OperatorSetPeers)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_Encrypt_Call) Return(bytes []byte, err error) *MockKMSClient_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_Encrypt_Call) RunAndReturn(run func(appID string, data []byte, operators *peering.OperatorSetPeers) ([]byte, error)) *MockKMSClient_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptForApp provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) EncryptForApp(appID string, plaintext []byte) ([]byte, error) {
	ret := _mock.Called(appID, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for EncryptForApp")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) ([]byte, error)); ok {
		return returnFunc(appID, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) []byte); ok {
		r0 = returnFunc(appID, plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(appID, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_EncryptForApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptForApp'
type MockKMSClient_EncryptForApp_Call struct {
	*mock.Call
}

// EncryptForApp is a helper method to define mock.On call
//   - appID string
//   - plaintext []byte
func (_e *MockKMSClient_Expecter) EncryptForApp(appID interface{}, plaintext interface{}) *MockKMSClient_EncryptForApp_Call {
	return &MockKMSClient_EncryptForApp_Call{Call: _e.mock.On("EncryptForApp", appID, plaintext)}
}

func (_c *MockKMSClient_EncryptForApp_Call) Run(run func(appID string, plaintext []byte)) *MockKMSClient_EncryptForApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMSClient_EncryptForApp_Call) Return(bytes []byte, err error) *MockKMSClient_EncryptForApp_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMSClient_EncryptForApp_Call) RunAndReturn(run func(appID string, plaintext []byte) ([]byte, error)) *MockKMSClient_EncryptForApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetEncryptedSecretsFromKMSNodesWithPartialSigs provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GetEncryptedSecretsFromKMSNodesWithPartialSigs(operators *peering.OperatorSetPeers, req types.SecretsRequestV1, rsaPrivateKeyPEM []byte) ([]types.SecretsResponseV1, map[common.Address]types.G1Point, error) {
	ret := _mock.Called(operators, req, rsaPrivateKeyPEM)

	if len(ret) == 0 {
		panic("no return value specified for GetEncryptedSecretsFromKMSNodesWithPartialSigs")
	}

	var r0 []types.SecretsResponseV1
	var r1 map[common.Address]types.G1Point
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*peering.OperatorSetPeers, types.SecretsRequestV1, []byte) ([]types.SecretsResponseV1, map[common.Address]types.G1Point, error)); ok {
		return returnFunc(operators, req, rsaPrivateKeyPEM)
	}
	if returnFunc, ok := ret.Get(0).(func(*peering.OperatorSetPeers, types.SecretsRequestV1, []byte) []types.SecretsResponseV1); ok {
		r0 = returnFunc(operators, req, rsaPrivateKeyPEM)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.SecretsResponseV1)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*peering.OperatorSetPeers, types.SecretsRequestV1, []byte) map[common.Address]types.G1Point); ok {
		r1 = returnFunc(operators, req, rsaPrivateKeyPEM)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[common.Address]types.G1Point)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*peering.OperatorSetPeers, types.SecretsRequestV1, []byte) error); ok {
		r2 = returnFunc(operators, req, rsaPrivateKeyPEM)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEncryptedSecretsFromKMSNodesWithPartialSigs'
type MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call struct {
	*mock.Call
}

// GetEncryptedSecretsFromKMSNodesWithPartialSigs is a helper method to define mock.On call
//   - operators *peering.OperatorSetPeers
//   - req types.SecretsRequestV1
//   - rsaPrivateKeyPEM []byte
func (_e *MockKMSClient_Expecter) GetEncryptedSecretsFromKMSNodesWithPartialSigs(operators interface{}, req interface{}, rsaPrivateKeyPEM interface{}) *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call {
	return &MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call{Call: _e.mock.On("GetEncryptedSecretsFromKMSNodesWithPartialSigs", operators, req, rsaPrivateKeyPEM)}
}

func (_c *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call) Run(run func(operators *peering.OperatorSetPeers, req types.SecretsRequestV1, rsaPrivateKeyPEM []byte)) *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *peering.OperatorSetPeers
		if args[0] != nil {
			arg0 = args[0].(*peering.OperatorSetPeers)
		}
		var arg1 types.SecretsRequestV1
		if args[1] != nil {
			arg1 = args[1].(types.SecretsRequestV1)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call) Return(secretsResponseV1s []types.SecretsResponseV1, addressToG1Point map[common.Address]types.G1Point, err error) *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call {
	_c.Call.Return(secretsResponseV1s, addressToG1Point, err)
	return _c
}

func (_c *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call) RunAndReturn(run func(operators *peering.OperatorSetPeers, req types.SecretsRequestV1, rsaPrivateKeyPEM []byte) ([]types.SecretsResponseV1, map[common.Address]types.G1Point, error)) *MockKMSClient_GetEncryptedSecretsFromKMSNodesWithPartialSigs_Call {
	_c.Call.Return(run)
	return _c
}

// GetMasterPublicKey provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GetMasterPublicKey(operators *peering.OperatorSetPeers) (*types.G2Point, error) {
	ret := _mock.Called(operators)

	if len(ret) == 0 {
		panic("no return value specified for GetMasterPublicKey")
	}

	var r0 *types.G2Point
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*peering.OperatorSetPeers) (*types.G2Point, error)); ok {
		return returnFunc(operators)
	}
	if returnFunc, ok := ret.Get(0).(func(*peering.OperatorSetPeers) *types.G2Point); ok {
		r0 = returnFunc(operators)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.G2Point)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*peering.OperatorSetPeers) error); ok {
		r1 = returnFunc(operators)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_GetMasterPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMasterPublicKey'
type MockKMSClient_GetMasterPublicKey_Call struct {
	*mock.Call
}

// GetMasterPublicKey is a helper method to define mock.On call
//   - operators *peering.OperatorSetPeers
func (_e *MockKMSClient_Expecter) GetMasterPublicKey(operators interface{}) *MockKMSClient_GetMasterPublicKey_Call {
	return &MockKMSClient_GetMasterPublicKey_Call{Call: _e.mock.On("GetMasterPublicKey", operators)}
}

func (_c *MockKMSClient_GetMasterPublicKey_Call) Run(run func(operators *peering.OperatorSetPeers)) *MockKMSClient_GetMasterPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *peering.OperatorSetPeers
		if args[0] != nil {
			arg0 = args[0].(*peering.OperatorSetPeers)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKMSClient_GetMasterPublicKey_Call) Return(g2Point *types.G2Point, err error) *MockKMSClient_GetMasterPublicKey_Call {
	_c.Call.Return(g2Point, err)
	return _c
}

func (_c *MockKMSClient_GetMasterPublicKey_Call) RunAndReturn(run func(operators *peering.OperatorSetPeers) (*types.G2Point, error)) *MockKMSClient_GetMasterPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperators provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GetOperators() (*peering.OperatorSetPeers, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperators")
	}

	var r0 *peering.OperatorSetPeers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*peering.OperatorSetPeers, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *peering.OperatorSetPeers); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peering.OperatorSetPeers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_GetOperators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperators'
type MockKMSClient_GetOperators_Call struct {
	*mock.Call
}

// GetOperators is a helper method to define mock.On call
func (_e *MockKMSClient_Expecter) GetOperators() *MockKMSClient_GetOperators_Call {
	return &MockKMSClient_GetOperators_Call{Call: _e.mock.On("GetOperators")}
}

func (_c *MockKMSClient_GetOperators_Call) Run(run func()) *MockKMSClient_GetOperators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKMSClient_GetOperators_Call) Return(operatorSetPeers *peering.OperatorSetPeers, err error) *MockKMSClient_GetOperators_Call {
	_c.Call.Return(operatorSetPeers, err)
	return _c
}

func (_c *MockKMSClient_GetOperators_Call) RunAndReturn(run func() (*peering.OperatorSetPeers, error)) *MockKMSClient_GetOperators_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicKeyForApp provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) GetPublicKeyForApp(appID string) (*types.G1Point, *types.G2Point, error) {
	ret := _mock.Called(appID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKeyForApp")
	}

	var r0 *types.G1Point
	var r1 *types.G2Point
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*types.G1Point, *types.G2Point, error)); ok {
		return returnFunc(appID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *types.G1Point); ok {
		r0 = returnFunc(appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.G1Point)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *types.G2Point); ok {
		r1 = returnFunc(appID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.G2Point)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(appID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKMSClient_GetPublicKeyForApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKeyForApp'
type MockKMSClient_GetPublicKeyForApp_Call struct {
	*mock.Call
}

// GetPublicKeyForApp is a helper method to define mock.On call
//   - appID string
func (_e *MockKMSClient_Expecter) GetPublicKeyForApp(appID interface{}) *MockKMSClient_GetPublicKeyForApp_Call {
	return &MockKMSClient_GetPublicKeyForApp_Call{Call: _e.mock.On("GetPublicKeyForApp", appID)}
}

func (_c *MockKMSClient_GetPublicKeyForApp_Call) Run(run func(appID string)) *MockKMSClient_GetPublicKeyForApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKMSClient_GetPublicKeyForApp_Call) Return(g1Point *types.G1Point, g2Point *types.G2Point, err error) *MockKMSClient_GetPublicKeyForApp_Call {
	_c.Call.Return(g1Point, g2Point, err)
	return _c
}

func (_c *MockKMSClient_GetPublicKeyForApp_Call) RunAndReturn(run func(appID string) (*types.G1Point, *types.G2Point, error)) *MockKMSClient_GetPublicKeyForApp_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveSecretsWithOptions provides a mock function for the type MockKMSClient
func (_mock *MockKMSClient) RetrieveSecretsWithOptions(appID string, opts *SecretsOptions) (*SecretsResult, error) {
	ret := _mock.Called(appID, opts)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveSecretsWithOptions")
	}

	var r0 *SecretsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *SecretsOptions) (*SecretsResult, error)); ok {
		return returnFunc(appID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *SecretsOptions) *SecretsResult); ok {
		r0 = returnFunc(appID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SecretsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *SecretsOptions) error); ok {
		r1 = returnFunc(appID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMSClient_RetrieveSecretsWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveSecretsWithOptions'
type MockKMSClient_RetrieveSecretsWithOptions_Call struct {
	*mock.Call
}

// RetrieveSecretsWithOptions is a helper method to define mock.On call
//   - appID string
//   - opts *SecretsOptions
func (_e *MockKMSClient_Expecter) RetrieveSecretsWithOptions(appID interface{}, opts interface{}) *MockKMSClient_RetrieveSecretsWithOptions_Call {
	return &MockKMSClient_RetrieveSecretsWithOptions_Call{Call: _e.mock.On("RetrieveSecretsWithOptions", appID, opts)}
}

func (_c *MockKMSClient_RetrieveSecretsWithOptions_Call) Run(run func(appID string, opts *SecretsOptions)) *MockKMSClient_RetrieveSecretsWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *SecretsOptions
		if args[1] != nil {
			arg1 = args[1].(*SecretsOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMSClient_RetrieveSecretsWithOptions_Call) Return(secretsResult *SecretsResult, err error) *MockKMSClient_RetrieveSecretsWithOptions_Call {
	_c.Call.Return(secretsResult, err)
	return _c
}

func (_c *MockKMSClient_RetrieveSecretsWithOptions_Call) RunAndReturn(run func(appID string, opts *SecretsOptions) (*SecretsResult, error)) *MockKMSClient_RetrieveSecretsWithOptions_Call {
	_c.Call.Return(run)
	return _c
}
