// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kmsClient

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/peering"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContractCaller creates a new instance of MockContractCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContractCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContractCaller {
	mock := &MockContractCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContractCaller is an autogenerated mock type for the ContractCaller type
type MockContractCaller struct {
	mock.Mock
}

type MockContractCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContractCaller) EXPECT() *MockContractCaller_Expecter {
	return &MockContractCaller_Expecter{mock: &_m.Mock}
}

// GetOperatorSetMembersWithPeering provides a mock function for the type MockContractCaller
func (_mock *MockContractCaller) GetOperatorSetMembersWithPeering(avsAddress string, operatorSetID uint32) (*peering.OperatorSetPeers, error) {
	ret := _mock.Called(avsAddress, operatorSetID)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSetMembersWithPeering")
	}

	var r0 *peering.OperatorSetPeers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint32) (*peering.OperatorSetPeers, error)); ok {
		return returnFunc(avsAddress, operatorSetID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint32) *peering.OperatorSetPeers); ok {
		r0 = returnFunc(avsAddress, operatorSetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peering.OperatorSetPeers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint32) error); ok {
		r1 = returnFunc(avsAddress, operatorSetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContractCaller_GetOperatorSetMembersWithPeering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorSetMembersWithPeering'
type MockContractCaller_GetOperatorSetMembersWithPeering_Call struct {
	*mock.Call
}

// GetOperatorSetMembersWithPeering is a helper method to define mock.On call
//   - avsAddress string
//   - operatorSetID uint32
func (_e *MockContractCaller_Expecter) GetOperatorSetMembersWithPeering(avsAddress interface{}, operatorSetID interface{}) *MockContractCaller_GetOperatorSetMembersWithPeering_Call {
	return &MockContractCaller_GetOperatorSetMembersWithPeering_Call{Call: _e.mock.On("GetOperatorSetMembersWithPeering", avsAddress, operatorSetID)}
}

func (_c *MockContractCaller_GetOperatorSetMembersWithPeering_Call) Run(run func(avsAddress string, operatorSetID uint32)) *MockContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContractCaller_GetOperatorSetMembersWithPeering_Call) Return(operatorSetPeers *peering.OperatorSetPeers, err error) *MockContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Return(operatorSetPeers, err)
	return _c
}

func (_c *MockContractCaller_GetOperatorSetMembersWithPeering_Call) RunAndReturn(run func(avsAddress string, operatorSetID uint32) (*peering.OperatorSetPeers, error)) *MockContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Return(run)
	return _c
}
