dir: "{{.InterfaceDir}}"
inpackage: true
filename: "mock_{{.InterfaceName}}.go"
all: false
packages:
  github.com/Layr-Labs/eigenx-kms-go/pkg/attestation:
    interfaces:
      AttestationMethod:
      AttestationVerifierInterface:
      BoundAttestationEvidenceVerifier:
  github.com/Layr-Labs/eigenx-kms-go/pkg/blockHandler:
    interfaces:
      IBlockHandler:
  github.com/Layr-Labs/eigenx-kms-go/pkg/clients/kmsClient:
    interfaces:
      ContractCaller:
      KMSClient:
  github.com/Layr-Labs/eigenx-kms-go/pkg/contractCaller/caller:
    interfaces:
      AppControllerInterface:
      AppUpgradedIterator:
  github.com/Layr-Labs/eigenx-kms-go/pkg/contractCaller:
    interfaces:
      IContractCaller:
  github.com/Layr-Labs/eigenx-kms-go/pkg/transportSigner:
    interfaces:
      ITransportSigner:
