// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transportSigner

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockITransportSigner creates a new instance of MockITransportSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransportSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransportSigner {
	mock := &MockITransportSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITransportSigner is an autogenerated mock type for the ITransportSigner type
type MockITransportSigner struct {
	mock.Mock
}

type MockITransportSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransportSigner) EXPECT() *MockITransportSigner_Expecter {
	return &MockITransportSigner_Expecter{mock: &_m.Mock}
}

// CreateAuthenticatedMessage provides a mock function for the type MockITransportSigner
func (_mock *MockITransportSigner) CreateAuthenticatedMessage(data []byte) (*SignedMessage, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthenticatedMessage")
	}

	var r0 *SignedMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*SignedMessage, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *SignedMessage); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignedMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransportSigner_CreateAuthenticatedMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthenticatedMessage'
type MockITransportSigner_CreateAuthenticatedMessage_Call struct {
	*mock.Call
}

// CreateAuthenticatedMessage is a helper method to define mock.On call
//   - data []byte
func (_e *MockITransportSigner_Expecter) CreateAuthenticatedMessage(data interface{}) *MockITransportSigner_CreateAuthenticatedMessage_Call {
	return &MockITransportSigner_CreateAuthenticatedMessage_Call{Call: _e.mock.On("CreateAuthenticatedMessage", data)}
}

func (_c *MockITransportSigner_CreateAuthenticatedMessage_Call) Run(run func(data []byte)) *MockITransportSigner_CreateAuthenticatedMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITransportSigner_CreateAuthenticatedMessage_Call) Return(signedMessage *SignedMessage, err error) *MockITransportSigner_CreateAuthenticatedMessage_Call {
	_c.Call.Return(signedMessage, err)
	return _c
}

func (_c *MockITransportSigner_CreateAuthenticatedMessage_Call) RunAndReturn(run func(data []byte) (*SignedMessage, error)) *MockITransportSigner_CreateAuthenticatedMessage_Call {
	_c.Call.Return(run)
	return _c
}
