// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetLatestRelease provides a mock function for the type MockClient
func (_mock *MockClient) GetLatestRelease(appID string) (*types.Release, error) {
	ret := _mock.Called(appID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRelease")
	}

	var r0 *types.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*types.Release, error)); ok {
		return returnFunc(appID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *types.Release); ok {
		r0 = returnFunc(appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRelease'
type MockClient_GetLatestRelease_Call struct {
	*mock.Call
}

// GetLatestRelease is a helper method to define mock.On call
//   - appID string
func (_e *MockClient_Expecter) GetLatestRelease(appID interface{}) *MockClient_GetLatestRelease_Call {
	return &MockClient_GetLatestRelease_Call{Call: _e.mock.On("GetLatestRelease", appID)}
}

func (_c *MockClient_GetLatestRelease_Call) Run(run func(appID string)) *MockClient_GetLatestRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetLatestRelease_Call) Return(release *types.Release, err error) *MockClient_GetLatestRelease_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *MockClient_GetLatestRelease_Call) RunAndReturn(run func(appID string) (*types.Release, error)) *MockClient_GetLatestRelease_Call {
	_c.Call.Return(run)
	return _c
}
