// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transactionSigner

import (
	"context"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITransactionSigner creates a new instance of MockITransactionSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionSigner {
	mock := &MockITransactionSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITransactionSigner is an autogenerated mock type for the ITransactionSigner type
type MockITransactionSigner struct {
	mock.Mock
}

type MockITransactionSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionSigner) EXPECT() *MockITransactionSigner_Expecter {
	return &MockITransactionSigner_Expecter{mock: &_m.Mock}
}

// EstimateGasPriceAndLimit provides a mock function for the type MockITransactionSigner
func (_mock *MockITransactionSigner) EstimateGasPriceAndLimit(ctx context.Context, tx *types.Transaction) (*big.Int, uint64, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGasPriceAndLimit")
	}

	var r0 *big.Int
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) (*big.Int, uint64, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) *big.Int); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Transaction) uint64); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *types.Transaction) error); ok {
		r2 = returnFunc(ctx, tx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockITransactionSigner_EstimateGasPriceAndLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGasPriceAndLimit'
type MockITransactionSigner_EstimateGasPriceAndLimit_Call struct {
	*mock.Call
}

// EstimateGasPriceAndLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
func (_e *MockITransactionSigner_Expecter) EstimateGasPriceAndLimit(ctx interface{}, tx interface{}) *MockITransactionSigner_EstimateGasPriceAndLimit_Call {
	return &MockITransactionSigner_EstimateGasPriceAndLimit_Call{Call: _e.mock.On("EstimateGasPriceAndLimit", ctx, tx)}
}

func (_c *MockITransactionSigner_EstimateGasPriceAndLimit_Call) Run(run func(ctx context.Context, tx *types.Transaction)) *MockITransactionSigner_EstimateGasPriceAndLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Transaction
		if args[1] != nil {
			arg1 = args[1].(*types.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionSigner_EstimateGasPriceAndLimit_Call) Return(intParam *big.Int, v uint64, err error) *MockITransactionSigner_EstimateGasPriceAndLimit_Call {
	_c.Call.Return(intParam, v, err)
	return _c
}

func (_c *MockITransactionSigner_EstimateGasPriceAndLimit_Call) RunAndReturn(run func(ctx context.Context, tx *types.Transaction) (*big.Int, uint64, error)) *MockITransactionSigner_EstimateGasPriceAndLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetFromAddress provides a mock function for the type MockITransactionSigner
func (_mock *MockITransactionSigner) GetFromAddress() common.Address {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFromAddress")
	}

	var r0 common.Address
	if returnFunc, ok := ret.Get(0).(func() common.Address); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}
	return r0
}

// MockITransactionSigner_GetFromAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromAddress'
type MockITransactionSigner_GetFromAddress_Call struct {
	*mock.Call
}

// GetFromAddress is a helper method to define mock.On call
func (_e *MockITransactionSigner_Expecter) GetFromAddress() *MockITransactionSigner_GetFromAddress_Call {
	return &MockITransactionSigner_GetFromAddress_Call{Call: _e.mock.On("GetFromAddress")}
}

func (_c *MockITransactionSigner_GetFromAddress_Call) Run(run func()) *MockITransactionSigner_GetFromAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockITransactionSigner_GetFromAddress_Call) Return(address common.Address) *MockITransactionSigner_GetFromAddress_Call {
	_c.Call.Return(address)
	return _c
}

func (_c *MockITransactionSigner_GetFromAddress_Call) RunAndReturn(run func() common.Address) *MockITransactionSigner_GetFromAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactOpts provides a mock function for the type MockITransactionSigner
func (_mock *MockITransactionSigner) GetTransactOpts(ctx context.Context) (*bind.TransactOpts, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactOpts")
	}

	var r0 *bind.TransactOpts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*bind.TransactOpts, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *bind.TransactOpts); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bind.TransactOpts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionSigner_GetTransactOpts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactOpts'
type MockITransactionSigner_GetTransactOpts_Call struct {
	*mock.Call
}

// GetTransactOpts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockITransactionSigner_Expecter) GetTransactOpts(ctx interface{}) *MockITransactionSigner_GetTransactOpts_Call {
	return &MockITransactionSigner_GetTransactOpts_Call{Call: _e.mock.On("GetTransactOpts", ctx)}
}

func (_c *MockITransactionSigner_GetTransactOpts_Call) Run(run func(ctx context.Context)) *MockITransactionSigner_GetTransactOpts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITransactionSigner_GetTransactOpts_Call) Return(v *bind.TransactOpts, err error) *MockITransactionSigner_GetTransactOpts_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockITransactionSigner_GetTransactOpts_Call) RunAndReturn(run func(ctx context.Context) (*bind.TransactOpts, error)) *MockITransactionSigner_GetTransactOpts_Call {
	_c.Call.Return(run)
	return _c
}

// SignAndSendTransaction provides a mock function for the type MockITransactionSigner
func (_mock *MockITransactionSigner) SignAndSendTransaction(ctx context.Context, tx *types.Transaction) (*types.Receipt, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SignAndSendTransaction")
	}

	var r0 *types.Receipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) (*types.Receipt, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) *types.Receipt); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionSigner_SignAndSendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAndSendTransaction'
type MockITransactionSigner_SignAndSendTransaction_Call struct {
	*mock.Call
}

// SignAndSendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
func (_e *MockITransactionSigner_Expecter) SignAndSendTransaction(ctx interface{}, tx interface{}) *MockITransactionSigner_SignAndSendTransaction_Call {
	return &MockITransactionSigner_SignAndSendTransaction_Call{Call: _e.mock.On("SignAndSendTransaction", ctx, tx)}
}

func (_c *MockITransactionSigner_SignAndSendTransaction_Call) Run(run func(ctx context.Context, tx *types.Transaction)) *MockITransactionSigner_SignAndSendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Transaction
		if args[1] != nil {
			arg1 = args[1].(*types.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionSigner_SignAndSendTransaction_Call) Return(receipt *types.Receipt, err error) *MockITransactionSigner_SignAndSendTransaction_Call {
	_c.Call.Return(receipt, err)
	return _c
}

func (_c *MockITransactionSigner_SignAndSendTransaction_Call) RunAndReturn(run func(ctx context.Context, tx *types.Transaction) (*types.Receipt, error)) *MockITransactionSigner_SignAndSendTransaction_Call {
	_c.Call.Return(run)
	return _c
}
