// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package blockHandler

import (
	"context"

	"github.com/Layr-Labs/chain-indexer/pkg/chainPollers"
	"github.com/Layr-Labs/chain-indexer/pkg/clients/ethereum"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIBlockHandler creates a new instance of MockIBlockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBlockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBlockHandler {
	mock := &MockIBlockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBlockHandler is an autogenerated mock type for the IBlockHandler type
type MockIBlockHandler struct {
	mock.Mock
}

type MockIBlockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBlockHandler) EXPECT() *MockIBlockHandler_Expecter {
	return &MockIBlockHandler_Expecter{mock: &_m.Mock}
}

// HandleBlock provides a mock function for the type MockIBlockHandler
func (_mock *MockIBlockHandler) HandleBlock(ctx context.Context, block *ethereum.EthereumBlock) error {
	ret := _mock.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for HandleBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ethereum.EthereumBlock) error); ok {
		r0 = returnFunc(ctx, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBlockHandler_HandleBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleBlock'
type MockIBlockHandler_HandleBlock_Call struct {
	*mock.Call
}

// HandleBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block *ethereum.EthereumBlock
func (_e *MockIBlockHandler_Expecter) HandleBlock(ctx interface{}, block interface{}) *MockIBlockHandler_HandleBlock_Call {
	return &MockIBlockHandler_HandleBlock_Call{Call: _e.mock.On("HandleBlock", ctx, block)}
}

func (_c *MockIBlockHandler_HandleBlock_Call) Run(run func(ctx context.Context, block *ethereum.EthereumBlock)) *MockIBlockHandler_HandleBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ethereum.EthereumBlock
		if args[1] != nil {
			arg1 = args[1].(*ethereum.EthereumBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockHandler_HandleBlock_Call) Return(err error) *MockIBlockHandler_HandleBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBlockHandler_HandleBlock_Call) RunAndReturn(run func(ctx context.Context, block *ethereum.EthereumBlock) error) *MockIBlockHandler_HandleBlock_Call {
	_c.Call.Return(run)
	return _c
}

// HandleLog provides a mock function for the type MockIBlockHandler
func (_mock *MockIBlockHandler) HandleLog(ctx context.Context, logWithBlock *chainPoller.LogWithBlock) error {
	ret := _mock.Called(ctx, logWithBlock)

	if len(ret) == 0 {
		panic("no return value specified for HandleLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chainPoller.LogWithBlock) error); ok {
		r0 = returnFunc(ctx, logWithBlock)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBlockHandler_HandleLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLog'
type MockIBlockHandler_HandleLog_Call struct {
	*mock.Call
}

// HandleLog is a helper method to define mock.On call
//   - ctx context.Context
//   - logWithBlock *chainPoller.LogWithBlock
func (_e *MockIBlockHandler_Expecter) HandleLog(ctx interface{}, logWithBlock interface{}) *MockIBlockHandler_HandleLog_Call {
	return &MockIBlockHandler_HandleLog_Call{Call: _e.mock.On("HandleLog", ctx, logWithBlock)}
}

func (_c *MockIBlockHandler_HandleLog_Call) Run(run func(ctx context.Context, logWithBlock *chainPoller.LogWithBlock)) *MockIBlockHandler_HandleLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chainPoller.LogWithBlock
		if args[1] != nil {
			arg1 = args[1].(*chainPoller.LogWithBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockHandler_HandleLog_Call) Return(err error) *MockIBlockHandler_HandleLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBlockHandler_HandleLog_Call) RunAndReturn(run func(ctx context.Context, logWithBlock *chainPoller.LogWithBlock) error) *MockIBlockHandler_HandleLog_Call {
	_c.Call.Return(run)
	return _c
}

// HandleReorgBlock provides a mock function for the type MockIBlockHandler
func (_mock *MockIBlockHandler) HandleReorgBlock(ctx context.Context, blockNumber uint64) {
	_mock.Called(ctx, blockNumber)
	return
}

// MockIBlockHandler_HandleReorgBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReorgBlock'
type MockIBlockHandler_HandleReorgBlock_Call struct {
	*mock.Call
}

// HandleReorgBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
func (_e *MockIBlockHandler_Expecter) HandleReorgBlock(ctx interface{}, blockNumber interface{}) *MockIBlockHandler_HandleReorgBlock_Call {
	return &MockIBlockHandler_HandleReorgBlock_Call{Call: _e.mock.On("HandleReorgBlock", ctx, blockNumber)}
}

func (_c *MockIBlockHandler_HandleReorgBlock_Call) Run(run func(ctx context.Context, blockNumber uint64)) *MockIBlockHandler_HandleReorgBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockHandler_HandleReorgBlock_Call) Return() *MockIBlockHandler_HandleReorgBlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBlockHandler_HandleReorgBlock_Call) RunAndReturn(run func(ctx context.Context, blockNumber uint64)) *MockIBlockHandler_HandleReorgBlock_Call {
	_c.Run(run)
	return _c
}

// ListenToChannel provides a mock function for the type MockIBlockHandler
func (_mock *MockIBlockHandler) ListenToChannel(ctx context.Context, handleFunc func(*ethereum.EthereumBlock)) {
	_mock.Called(ctx, handleFunc)
	return
}

// MockIBlockHandler_ListenToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenToChannel'
type MockIBlockHandler_ListenToChannel_Call struct {
	*mock.Call
}

// ListenToChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - handleFunc func(*ethereum.EthereumBlock)
func (_e *MockIBlockHandler_Expecter) ListenToChannel(ctx interface{}, handleFunc interface{}) *MockIBlockHandler_ListenToChannel_Call {
	return &MockIBlockHandler_ListenToChannel_Call{Call: _e.mock.On("ListenToChannel", ctx, handleFunc)}
}

func (_c *MockIBlockHandler_ListenToChannel_Call) Run(run func(ctx context.Context, handleFunc func(*ethereum.EthereumBlock))) *MockIBlockHandler_ListenToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(*ethereum.EthereumBlock)
		if args[1] != nil {
			arg1 = args[1].(func(*ethereum.EthereumBlock))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockHandler_ListenToChannel_Call) Return() *MockIBlockHandler_ListenToChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBlockHandler_ListenToChannel_Call) RunAndReturn(run func(ctx context.Context, handleFunc func(*ethereum.EthereumBlock))) *MockIBlockHandler_ListenToChannel_Call {
	_c.Run(run)
	return _c
}
