// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reshare

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProtocol creates a new instance of MockProtocol. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtocol(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtocol {
	mock := &MockProtocol{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtocol is an autogenerated mock type for the Protocol type
type MockProtocol struct {
	mock.Mock
}

type MockProtocol_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtocol) EXPECT() *MockProtocol_Expecter {
	return &MockProtocol_Expecter{mock: &_m.Mock}
}

// ComputeNewKeyShare provides a mock function for the type MockProtocol
func (_mock *MockProtocol) ComputeNewKeyShare(dealerIDs []int64, shares map[int64]*fr.Element, allCommitments [][]types.G2Point) (*types.KeyShareVersion, error) {
	ret := _mock.Called(dealerIDs, shares, allCommitments)

	if len(ret) == 0 {
		panic("no return value specified for ComputeNewKeyShare")
	}

	var r0 *types.KeyShareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64, map[int64]*fr.Element, [][]types.G2Point) (*types.KeyShareVersion, error)); ok {
		return returnFunc(dealerIDs, shares, allCommitments)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64, map[int64]*fr.Element, [][]types.G2Point) *types.KeyShareVersion); ok {
		r0 = returnFunc(dealerIDs, shares, allCommitments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.KeyShareVersion)
		}
	}
	if len(ret) > 1 {
		if returnFunc, ok := ret.Get(1).(func([]int64, map[int64]*fr.Element, [][]types.G2Point) error); ok {
			r1 = returnFunc(dealerIDs, shares, allCommitments)
		} else {
			r1 = ret.Error(1)
		}
	}
	return r0, r1
}

// MockProtocol_ComputeNewKeyShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeNewKeyShare'
type MockProtocol_ComputeNewKeyShare_Call struct {
	*mock.Call
}

// ComputeNewKeyShare is a helper method to define mock.On call
//   - dealerIDs []int64
//   - shares map[int64]*fr.Element
//   - allCommitments [][]types.G2Point
func (_e *MockProtocol_Expecter) ComputeNewKeyShare(dealerIDs interface{}, shares interface{}, allCommitments interface{}) *MockProtocol_ComputeNewKeyShare_Call {
	return &MockProtocol_ComputeNewKeyShare_Call{Call: _e.mock.On("ComputeNewKeyShare", dealerIDs, shares, allCommitments)}
}

func (_c *MockProtocol_ComputeNewKeyShare_Call) Run(run func(dealerIDs []int64, shares map[int64]*fr.Element, allCommitments [][]types.G2Point)) *MockProtocol_ComputeNewKeyShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		var arg1 map[int64]*fr.Element
		if args[1] != nil {
			arg1 = args[1].(map[int64]*fr.Element)
		}
		var arg2 [][]types.G2Point
		if args[2] != nil {
			arg2 = args[2].([][]types.G2Point)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProtocol_ComputeNewKeyShare_Call) Return(keyShareVersion *types.KeyShareVersion, err error) *MockProtocol_ComputeNewKeyShare_Call {
	_c.Call.Return(keyShareVersion, err)
	return _c
}

func (_c *MockProtocol_ComputeNewKeyShare_Call) RunAndReturn(run func(dealerIDs []int64, shares map[int64]*fr.Element, allCommitments [][]types.G2Point) (*types.KeyShareVersion, error)) *MockProtocol_ComputeNewKeyShare_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateNewShares provides a mock function for the type MockProtocol
func (_mock *MockProtocol) GenerateNewShares(currentShare *fr.Element, newThreshold int) (map[int64]*fr.Element, []types.G2Point, error) {
	ret := _mock.Called(currentShare, newThreshold)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNewShares")
	}

	var r0 map[int64]*fr.Element
	var r1 []types.G2Point
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*fr.Element, int) (map[int64]*fr.Element, []types.G2Point, error)); ok {
		return returnFunc(currentShare, newThreshold)
	}
	if returnFunc, ok := ret.Get(0).(func(*fr.Element, int) map[int64]*fr.Element); ok {
		r0 = returnFunc(currentShare, newThreshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]*fr.Element)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*fr.Element, int) []types.G2Point); ok {
		r1 = returnFunc(currentShare, newThreshold)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]types.G2Point)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*fr.Element, int) error); ok {
		r2 = returnFunc(currentShare, newThreshold)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProtocol_GenerateNewShares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateNewShares'
type MockProtocol_GenerateNewShares_Call struct {
	*mock.Call
}

// GenerateNewShares is a helper method to define mock.On call
//   - currentShare *fr.Element
//   - newThreshold int
func (_e *MockProtocol_Expecter) GenerateNewShares(currentShare interface{}, newThreshold interface{}) *MockProtocol_GenerateNewShares_Call {
	return &MockProtocol_GenerateNewShares_Call{Call: _e.mock.On("GenerateNewShares", currentShare, newThreshold)}
}

func (_c *MockProtocol_GenerateNewShares_Call) Run(run func(currentShare *fr.Element, newThreshold int)) *MockProtocol_GenerateNewShares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fr.Element
		if args[0] != nil {
			arg0 = args[0].(*fr.Element)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProtocol_GenerateNewShares_Call) Return(intToElement map[int64]*fr.Element, g2Points []types.G2Point, err error) *MockProtocol_GenerateNewShares_Call {
	_c.Call.Return(intToElement, g2Points, err)
	return _c
}

func (_c *MockProtocol_GenerateNewShares_Call) RunAndReturn(run func(currentShare *fr.Element, newThreshold int) (map[int64]*fr.Element, []types.G2Point, error)) *MockProtocol_GenerateNewShares_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyNewShare provides a mock function for the type MockProtocol
func (_mock *MockProtocol) VerifyNewShare(fromID int64, share *fr.Element, commitments []types.G2Point) bool {
	ret := _mock.Called(fromID, share, commitments)

	if len(ret) == 0 {
		panic("no return value specified for VerifyNewShare")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int64, *fr.Element, []types.G2Point) bool); ok {
		r0 = returnFunc(fromID, share, commitments)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProtocol_VerifyNewShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyNewShare'
type MockProtocol_VerifyNewShare_Call struct {
	*mock.Call
}

// VerifyNewShare is a helper method to define mock.On call
//   - fromID int64
//   - share *fr.Element
//   - commitments []types.G2Point
func (_e *MockProtocol_Expecter) VerifyNewShare(fromID interface{}, share interface{}, commitments interface{}) *MockProtocol_VerifyNewShare_Call {
	return &MockProtocol_VerifyNewShare_Call{Call: _e.mock.On("VerifyNewShare", fromID, share, commitments)}
}

func (_c *MockProtocol_VerifyNewShare_Call) Run(run func(fromID int64, share *fr.Element, commitments []types.G2Point)) *MockProtocol_VerifyNewShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 *fr.Element
		if args[1] != nil {
			arg1 = args[1].(*fr.Element)
		}
		var arg2 []types.G2Point
		if args[2] != nil {
			arg2 = args[2].([]types.G2Point)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProtocol_VerifyNewShare_Call) Return(b bool) *MockProtocol_VerifyNewShare_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProtocol_VerifyNewShare_Call) RunAndReturn(run func(fromID int64, share *fr.Element, commitments []types.G2Point) bool) *MockProtocol_VerifyNewShare_Call {
	_c.Call.Return(run)
	return _c
}
