// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dkg

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProtocol creates a new instance of MockProtocol. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtocol(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtocol {
	mock := &MockProtocol{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtocol is an autogenerated mock type for the Protocol type
type MockProtocol struct {
	mock.Mock
}

type MockProtocol_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtocol) EXPECT() *MockProtocol_Expecter {
	return &MockProtocol_Expecter{mock: &_m.Mock}
}

// FinalizeKeyShare provides a mock function for the type MockProtocol
func (_mock *MockProtocol) FinalizeKeyShare(shares map[int]*fr.Element, allCommitments [][]types.G2Point, participantIDs []int) *types.KeyShareVersion {
	ret := _mock.Called(shares, allCommitments, participantIDs)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeKeyShare")
	}

	var r0 *types.KeyShareVersion
	if returnFunc, ok := ret.Get(0).(func(map[int]*fr.Element, [][]types.G2Point, []int) *types.KeyShareVersion); ok {
		r0 = returnFunc(shares, allCommitments, participantIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.KeyShareVersion)
		}
	}
	return r0
}

// MockProtocol_FinalizeKeyShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeKeyShare'
type MockProtocol_FinalizeKeyShare_Call struct {
	*mock.Call
}

// FinalizeKeyShare is a helper method to define mock.On call
//   - shares map[int]*fr.Element
//   - allCommitments [][]types.G2Point
//   - participantIDs []int
func (_e *MockProtocol_Expecter) FinalizeKeyShare(shares interface{}, allCommitments interface{}, participantIDs interface{}) *MockProtocol_FinalizeKeyShare_Call {
	return &MockProtocol_FinalizeKeyShare_Call{Call: _e.mock.On("FinalizeKeyShare", shares, allCommitments, participantIDs)}
}

func (_c *MockProtocol_FinalizeKeyShare_Call) Run(run func(shares map[int]*fr.Element, allCommitments [][]types.G2Point, participantIDs []int)) *MockProtocol_FinalizeKeyShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[int]*fr.Element
		if args[0] != nil {
			arg0 = args[0].(map[int]*fr.Element)
		}
		var arg1 [][]types.G2Point
		if args[1] != nil {
			arg1 = args[1].([][]types.G2Point)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProtocol_FinalizeKeyShare_Call) Return(keyShareVersion *types.KeyShareVersion) *MockProtocol_FinalizeKeyShare_Call {
	_c.Call.Return(keyShareVersion)
	return _c
}

func (_c *MockProtocol_FinalizeKeyShare_Call) RunAndReturn(run func(shares map[int]*fr.Element, allCommitments [][]types.G2Point, participantIDs []int) *types.KeyShareVersion) *MockProtocol_FinalizeKeyShare_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateShares provides a mock function for the type MockProtocol
func (_mock *MockProtocol) GenerateShares() (map[int]*fr.Element, []types.G2Point, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateShares")
	}

	var r0 map[int]*fr.Element
	var r1 []types.G2Point
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (map[int]*fr.Element, []types.G2Point, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[int]*fr.Element); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]*fr.Element)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []types.G2Point); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]types.G2Point)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProtocol_GenerateShares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateShares'
type MockProtocol_GenerateShares_Call struct {
	*mock.Call
}

// GenerateShares is a helper method to define mock.On call
func (_e *MockProtocol_Expecter) GenerateShares() *MockProtocol_GenerateShares_Call {
	return &MockProtocol_GenerateShares_Call{Call: _e.mock.On("GenerateShares")}
}

func (_c *MockProtocol_GenerateShares_Call) Run(run func()) *MockProtocol_GenerateShares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocol_GenerateShares_Call) Return(intToElement map[int]*fr.Element, g2Points []types.G2Point, err error) *MockProtocol_GenerateShares_Call {
	_c.Call.Return(intToElement, g2Points, err)
	return _c
}

func (_c *MockProtocol_GenerateShares_Call) RunAndReturn(run func() (map[int]*fr.Element, []types.G2Point, error)) *MockProtocol_GenerateShares_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyShare provides a mock function for the type MockProtocol
func (_mock *MockProtocol) VerifyShare(fromID int, share *fr.Element, commitments []types.G2Point) bool {
	ret := _mock.Called(fromID, share, commitments)

	if len(ret) == 0 {
		panic("no return value specified for VerifyShare")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int, *fr.Element, []types.G2Point) bool); ok {
		r0 = returnFunc(fromID, share, commitments)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProtocol_VerifyShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyShare'
type MockProtocol_VerifyShare_Call struct {
	*mock.Call
}

// VerifyShare is a helper method to define mock.On call
//   - fromID int
//   - share *fr.Element
//   - commitments []types.G2Point
func (_e *MockProtocol_Expecter) VerifyShare(fromID interface{}, share interface{}, commitments interface{}) *MockProtocol_VerifyShare_Call {
	return &MockProtocol_VerifyShare_Call{Call: _e.mock.On("VerifyShare", fromID, share, commitments)}
}

func (_c *MockProtocol_VerifyShare_Call) Run(run func(fromID int, share *fr.Element, commitments []types.G2Point)) *MockProtocol_VerifyShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 *fr.Element
		if args[1] != nil {
			arg1 = args[1].(*fr.Element)
		}
		var arg2 []types.G2Point
		if args[2] != nil {
			arg2 = args[2].([]types.G2Point)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProtocol_VerifyShare_Call) Return(b bool) *MockProtocol_VerifyShare_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProtocol_VerifyShare_Call) RunAndReturn(run func(fromID int, share *fr.Element, commitments []types.G2Point) bool) *MockProtocol_VerifyShare_Call {
	_c.Call.Return(run)
	return _c
}
