// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package peering

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPeeringDataFetcher creates a new instance of MockIPeeringDataFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPeeringDataFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPeeringDataFetcher {
	mock := &MockIPeeringDataFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPeeringDataFetcher is an autogenerated mock type for the IPeeringDataFetcher type
type MockIPeeringDataFetcher struct {
	mock.Mock
}

type MockIPeeringDataFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPeeringDataFetcher) EXPECT() *MockIPeeringDataFetcher_Expecter {
	return &MockIPeeringDataFetcher_Expecter{mock: &_m.Mock}
}

// ListKMSOperators provides a mock function for the type MockIPeeringDataFetcher
func (_mock *MockIPeeringDataFetcher) ListKMSOperators(ctx context.Context, avsAddress string, operatorSetId uint32) (*OperatorSetPeers, error) {
	ret := _mock.Called(ctx, avsAddress, operatorSetId)

	if len(ret) == 0 {
		panic("no return value specified for ListKMSOperators")
	}

	var r0 *OperatorSetPeers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint32) (*OperatorSetPeers, error)); ok {
		return returnFunc(ctx, avsAddress, operatorSetId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint32) *OperatorSetPeers); ok {
		r0 = returnFunc(ctx, avsAddress, operatorSetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OperatorSetPeers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint32) error); ok {
		r1 = returnFunc(ctx, avsAddress, operatorSetId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPeeringDataFetcher_ListKMSOperators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKMSOperators'
type MockIPeeringDataFetcher_ListKMSOperators_Call struct {
	*mock.Call
}

// ListKMSOperators is a helper method to define mock.On call
//   - ctx context.Context
//   - avsAddress string
//   - operatorSetId uint32
func (_e *MockIPeeringDataFetcher_Expecter) ListKMSOperators(ctx interface{}, avsAddress interface{}, operatorSetId interface{}) *MockIPeeringDataFetcher_ListKMSOperators_Call {
	return &MockIPeeringDataFetcher_ListKMSOperators_Call{Call: _e.mock.On("ListKMSOperators", ctx, avsAddress, operatorSetId)}
}

func (_c *MockIPeeringDataFetcher_ListKMSOperators_Call) Run(run func(ctx context.Context, avsAddress string, operatorSetId uint32)) *MockIPeeringDataFetcher_ListKMSOperators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPeeringDataFetcher_ListKMSOperators_Call) Return(operatorSetPeers *OperatorSetPeers, err error) *MockIPeeringDataFetcher_ListKMSOperators_Call {
	_c.Call.Return(operatorSetPeers, err)
	return _c
}

func (_c *MockIPeeringDataFetcher_ListKMSOperators_Call) RunAndReturn(run func(ctx context.Context, avsAddress string, operatorSetId uint32) (*OperatorSetPeers, error)) *MockIPeeringDataFetcher_ListKMSOperators_Call {
	_c.Call.Return(run)
	return _c
}
