// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package persistence

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockINodePersistence creates a new instance of MockINodePersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockINodePersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockINodePersistence {
	mock := &MockINodePersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockINodePersistence is an autogenerated mock type for the INodePersistence type
type MockINodePersistence struct {
	mock.Mock
}

type MockINodePersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockINodePersistence) EXPECT() *MockINodePersistence_Expecter {
	return &MockINodePersistence_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockINodePersistence_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) Close() *MockINodePersistence_Close_Call {
	return &MockINodePersistence_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockINodePersistence_Close_Call) Run(run func()) *MockINodePersistence_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_Close_Call) Return(err error) *MockINodePersistence_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_Close_Call) RunAndReturn(run func() error) *MockINodePersistence_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyShareVersion provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) DeleteKeyShareVersion(epoch int64) error {
	ret := _mock.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyShareVersion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(epoch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_DeleteKeyShareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyShareVersion'
type MockINodePersistence_DeleteKeyShareVersion_Call struct {
	*mock.Call
}

// DeleteKeyShareVersion is a helper method to define mock.On call
//   - epoch int64
func (_e *MockINodePersistence_Expecter) DeleteKeyShareVersion(epoch interface{}) *MockINodePersistence_DeleteKeyShareVersion_Call {
	return &MockINodePersistence_DeleteKeyShareVersion_Call{Call: _e.mock.On("DeleteKeyShareVersion", epoch)}
}

func (_c *MockINodePersistence_DeleteKeyShareVersion_Call) Run(run func(epoch int64)) *MockINodePersistence_DeleteKeyShareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_DeleteKeyShareVersion_Call) Return(err error) *MockINodePersistence_DeleteKeyShareVersion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_DeleteKeyShareVersion_Call) RunAndReturn(run func(epoch int64) error) *MockINodePersistence_DeleteKeyShareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProtocolSession provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) DeleteProtocolSession(sessionTimestamp int64) error {
	ret := _mock.Called(sessionTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProtocolSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(sessionTimestamp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_DeleteProtocolSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProtocolSession'
type MockINodePersistence_DeleteProtocolSession_Call struct {
	*mock.Call
}

// DeleteProtocolSession is a helper method to define mock.On call
//   - sessionTimestamp int64
func (_e *MockINodePersistence_Expecter) DeleteProtocolSession(sessionTimestamp interface{}) *MockINodePersistence_DeleteProtocolSession_Call {
	return &MockINodePersistence_DeleteProtocolSession_Call{Call: _e.mock.On("DeleteProtocolSession", sessionTimestamp)}
}

func (_c *MockINodePersistence_DeleteProtocolSession_Call) Run(run func(sessionTimestamp int64)) *MockINodePersistence_DeleteProtocolSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_DeleteProtocolSession_Call) Return(err error) *MockINodePersistence_DeleteProtocolSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_DeleteProtocolSession_Call) RunAndReturn(run func(sessionTimestamp int64) error) *MockINodePersistence_DeleteProtocolSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveVersionEpoch provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) GetActiveVersionEpoch() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveVersionEpoch")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_GetActiveVersionEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveVersionEpoch'
type MockINodePersistence_GetActiveVersionEpoch_Call struct {
	*mock.Call
}

// GetActiveVersionEpoch is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) GetActiveVersionEpoch() *MockINodePersistence_GetActiveVersionEpoch_Call {
	return &MockINodePersistence_GetActiveVersionEpoch_Call{Call: _e.mock.On("GetActiveVersionEpoch")}
}

func (_c *MockINodePersistence_GetActiveVersionEpoch_Call) Run(run func()) *MockINodePersistence_GetActiveVersionEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_GetActiveVersionEpoch_Call) Return(n int64, err error) *MockINodePersistence_GetActiveVersionEpoch_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockINodePersistence_GetActiveVersionEpoch_Call) RunAndReturn(run func() (int64, error)) *MockINodePersistence_GetActiveVersionEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) HealthCheck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockINodePersistence_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) HealthCheck() *MockINodePersistence_HealthCheck_Call {
	return &MockINodePersistence_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockINodePersistence_HealthCheck_Call) Run(run func()) *MockINodePersistence_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_HealthCheck_Call) Return(err error) *MockINodePersistence_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_HealthCheck_Call) RunAndReturn(run func() error) *MockINodePersistence_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyShareVersions provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) ListKeyShareVersions() ([]*types.KeyShareVersion, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListKeyShareVersions")
	}

	var r0 []*types.KeyShareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*types.KeyShareVersion, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*types.KeyShareVersion); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.KeyShareVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_ListKeyShareVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyShareVersions'
type MockINodePersistence_ListKeyShareVersions_Call struct {
	*mock.Call
}

// ListKeyShareVersions is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) ListKeyShareVersions() *MockINodePersistence_ListKeyShareVersions_Call {
	return &MockINodePersistence_ListKeyShareVersions_Call{Call: _e.mock.On("ListKeyShareVersions")}
}

func (_c *MockINodePersistence_ListKeyShareVersions_Call) Run(run func()) *MockINodePersistence_ListKeyShareVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_ListKeyShareVersions_Call) Return(keyShareVersions []*types.KeyShareVersion, err error) *MockINodePersistence_ListKeyShareVersions_Call {
	_c.Call.Return(keyShareVersions, err)
	return _c
}

func (_c *MockINodePersistence_ListKeyShareVersions_Call) RunAndReturn(run func() ([]*types.KeyShareVersion, error)) *MockINodePersistence_ListKeyShareVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListProtocolSessions provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) ListProtocolSessions() ([]*ProtocolSessionState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListProtocolSessions")
	}

	var r0 []*ProtocolSessionState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*ProtocolSessionState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*ProtocolSessionState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ProtocolSessionState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_ListProtocolSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProtocolSessions'
type MockINodePersistence_ListProtocolSessions_Call struct {
	*mock.Call
}

// ListProtocolSessions is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) ListProtocolSessions() *MockINodePersistence_ListProtocolSessions_Call {
	return &MockINodePersistence_ListProtocolSessions_Call{Call: _e.mock.On("ListProtocolSessions")}
}

func (_c *MockINodePersistence_ListProtocolSessions_Call) Run(run func()) *MockINodePersistence_ListProtocolSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_ListProtocolSessions_Call) Return(protocolSessionStates []*ProtocolSessionState, err error) *MockINodePersistence_ListProtocolSessions_Call {
	_c.Call.Return(protocolSessionStates, err)
	return _c
}

func (_c *MockINodePersistence_ListProtocolSessions_Call) RunAndReturn(run func() ([]*ProtocolSessionState, error)) *MockINodePersistence_ListProtocolSessions_Call {
	_c.Call.Return(run)
	return _c
}

// LoadKeyShareVersion provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) LoadKeyShareVersion(epoch int64) (*types.KeyShareVersion, error) {
	ret := _mock.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for LoadKeyShareVersion")
	}

	var r0 *types.KeyShareVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*types.KeyShareVersion, error)); ok {
		return returnFunc(epoch)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *types.KeyShareVersion); ok {
		r0 = returnFunc(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.KeyShareVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(epoch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_LoadKeyShareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadKeyShareVersion'
type MockINodePersistence_LoadKeyShareVersion_Call struct {
	*mock.Call
}

// LoadKeyShareVersion is a helper method to define mock.On call
//   - epoch int64
func (_e *MockINodePersistence_Expecter) LoadKeyShareVersion(epoch interface{}) *MockINodePersistence_LoadKeyShareVersion_Call {
	return &MockINodePersistence_LoadKeyShareVersion_Call{Call: _e.mock.On("LoadKeyShareVersion", epoch)}
}

func (_c *MockINodePersistence_LoadKeyShareVersion_Call) Run(run func(epoch int64)) *MockINodePersistence_LoadKeyShareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_LoadKeyShareVersion_Call) Return(keyShareVersion *types.KeyShareVersion, err error) *MockINodePersistence_LoadKeyShareVersion_Call {
	_c.Call.Return(keyShareVersion, err)
	return _c
}

func (_c *MockINodePersistence_LoadKeyShareVersion_Call) RunAndReturn(run func(epoch int64) (*types.KeyShareVersion, error)) *MockINodePersistence_LoadKeyShareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// LoadNodeState provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) LoadNodeState() (*NodeState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadNodeState")
	}

	var r0 *NodeState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*NodeState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *NodeState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NodeState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_LoadNodeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadNodeState'
type MockINodePersistence_LoadNodeState_Call struct {
	*mock.Call
}

// LoadNodeState is a helper method to define mock.On call
func (_e *MockINodePersistence_Expecter) LoadNodeState() *MockINodePersistence_LoadNodeState_Call {
	return &MockINodePersistence_LoadNodeState_Call{Call: _e.mock.On("LoadNodeState")}
}

func (_c *MockINodePersistence_LoadNodeState_Call) Run(run func()) *MockINodePersistence_LoadNodeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINodePersistence_LoadNodeState_Call) Return(nodeState *NodeState, err error) *MockINodePersistence_LoadNodeState_Call {
	_c.Call.Return(nodeState, err)
	return _c
}

func (_c *MockINodePersistence_LoadNodeState_Call) RunAndReturn(run func() (*NodeState, error)) *MockINodePersistence_LoadNodeState_Call {
	_c.Call.Return(run)
	return _c
}

// LoadProtocolSession provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) LoadProtocolSession(sessionTimestamp int64) (*ProtocolSessionState, error) {
	ret := _mock.Called(sessionTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for LoadProtocolSession")
	}

	var r0 *ProtocolSessionState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*ProtocolSessionState, error)); ok {
		return returnFunc(sessionTimestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *ProtocolSessionState); ok {
		r0 = returnFunc(sessionTimestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProtocolSessionState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(sessionTimestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockINodePersistence_LoadProtocolSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadProtocolSession'
type MockINodePersistence_LoadProtocolSession_Call struct {
	*mock.Call
}

// LoadProtocolSession is a helper method to define mock.On call
//   - sessionTimestamp int64
func (_e *MockINodePersistence_Expecter) LoadProtocolSession(sessionTimestamp interface{}) *MockINodePersistence_LoadProtocolSession_Call {
	return &MockINodePersistence_LoadProtocolSession_Call{Call: _e.mock.On("LoadProtocolSession", sessionTimestamp)}
}

func (_c *MockINodePersistence_LoadProtocolSession_Call) Run(run func(sessionTimestamp int64)) *MockINodePersistence_LoadProtocolSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_LoadProtocolSession_Call) Return(protocolSessionState *ProtocolSessionState, err error) *MockINodePersistence_LoadProtocolSession_Call {
	_c.Call.Return(protocolSessionState, err)
	return _c
}

func (_c *MockINodePersistence_LoadProtocolSession_Call) RunAndReturn(run func(sessionTimestamp int64) (*ProtocolSessionState, error)) *MockINodePersistence_LoadProtocolSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveKeyShareVersion provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) SaveKeyShareVersion(version *types.KeyShareVersion) error {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for SaveKeyShareVersion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*types.KeyShareVersion) error); ok {
		r0 = returnFunc(version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_SaveKeyShareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKeyShareVersion'
type MockINodePersistence_SaveKeyShareVersion_Call struct {
	*mock.Call
}

// SaveKeyShareVersion is a helper method to define mock.On call
//   - version *types.KeyShareVersion
func (_e *MockINodePersistence_Expecter) SaveKeyShareVersion(version interface{}) *MockINodePersistence_SaveKeyShareVersion_Call {
	return &MockINodePersistence_SaveKeyShareVersion_Call{Call: _e.mock.On("SaveKeyShareVersion", version)}
}

func (_c *MockINodePersistence_SaveKeyShareVersion_Call) Run(run func(version *types.KeyShareVersion)) *MockINodePersistence_SaveKeyShareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types.KeyShareVersion
		if args[0] != nil {
			arg0 = args[0].(*types.KeyShareVersion)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_SaveKeyShareVersion_Call) Return(err error) *MockINodePersistence_SaveKeyShareVersion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_SaveKeyShareVersion_Call) RunAndReturn(run func(version *types.KeyShareVersion) error) *MockINodePersistence_SaveKeyShareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNodeState provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) SaveNodeState(state *NodeState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SaveNodeState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*NodeState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_SaveNodeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNodeState'
type MockINodePersistence_SaveNodeState_Call struct {
	*mock.Call
}

// SaveNodeState is a helper method to define mock.On call
//   - state *NodeState
func (_e *MockINodePersistence_Expecter) SaveNodeState(state interface{}) *MockINodePersistence_SaveNodeState_Call {
	return &MockINodePersistence_SaveNodeState_Call{Call: _e.mock.On("SaveNodeState", state)}
}

func (_c *MockINodePersistence_SaveNodeState_Call) Run(run func(state *NodeState)) *MockINodePersistence_SaveNodeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *NodeState
		if args[0] != nil {
			arg0 = args[0].(*NodeState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_SaveNodeState_Call) Return(err error) *MockINodePersistence_SaveNodeState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_SaveNodeState_Call) RunAndReturn(run func(state *NodeState) error) *MockINodePersistence_SaveNodeState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProtocolSession provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) SaveProtocolSession(session *ProtocolSessionState) error {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for SaveProtocolSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*ProtocolSessionState) error); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_SaveProtocolSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProtocolSession'
type MockINodePersistence_SaveProtocolSession_Call struct {
	*mock.Call
}

// SaveProtocolSession is a helper method to define mock.On call
//   - session *ProtocolSessionState
func (_e *MockINodePersistence_Expecter) SaveProtocolSession(session interface{}) *MockINodePersistence_SaveProtocolSession_Call {
	return &MockINodePersistence_SaveProtocolSession_Call{Call: _e.mock.On("SaveProtocolSession", session)}
}

func (_c *MockINodePersistence_SaveProtocolSession_Call) Run(run func(session *ProtocolSessionState)) *MockINodePersistence_SaveProtocolSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ProtocolSessionState
		if args[0] != nil {
			arg0 = args[0].(*ProtocolSessionState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_SaveProtocolSession_Call) Return(err error) *MockINodePersistence_SaveProtocolSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_SaveProtocolSession_Call) RunAndReturn(run func(session *ProtocolSessionState) error) *MockINodePersistence_SaveProtocolSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveVersionEpoch provides a mock function for the type MockINodePersistence
func (_mock *MockINodePersistence) SetActiveVersionEpoch(epoch int64) error {
	ret := _mock.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveVersionEpoch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(epoch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockINodePersistence_SetActiveVersionEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveVersionEpoch'
type MockINodePersistence_SetActiveVersionEpoch_Call struct {
	*mock.Call
}

// SetActiveVersionEpoch is a helper method to define mock.On call
//   - epoch int64
func (_e *MockINodePersistence_Expecter) SetActiveVersionEpoch(epoch interface{}) *MockINodePersistence_SetActiveVersionEpoch_Call {
	return &MockINodePersistence_SetActiveVersionEpoch_Call{Call: _e.mock.On("SetActiveVersionEpoch", epoch)}
}

func (_c *MockINodePersistence_SetActiveVersionEpoch_Call) Run(run func(epoch int64)) *MockINodePersistence_SetActiveVersionEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockINodePersistence_SetActiveVersionEpoch_Call) Return(err error) *MockINodePersistence_SetActiveVersionEpoch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockINodePersistence_SetActiveVersionEpoch_Call) RunAndReturn(run func(epoch int64) error) *MockINodePersistence_SetActiveVersionEpoch_Call {
	_c.Call.Return(run)
	return _c
}
