// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package caller

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppUpgradedIterator creates a new instance of MockAppUpgradedIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppUpgradedIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppUpgradedIterator {
	mock := &MockAppUpgradedIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppUpgradedIterator is an autogenerated mock type for the AppUpgradedIterator type
type MockAppUpgradedIterator struct {
	mock.Mock
}

type MockAppUpgradedIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppUpgradedIterator) EXPECT() *MockAppUpgradedIterator_Expecter {
	return &MockAppUpgradedIterator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockAppUpgradedIterator
func (_mock *MockAppUpgradedIterator) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppUpgradedIterator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAppUpgradedIterator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAppUpgradedIterator_Expecter) Close() *MockAppUpgradedIterator_Close_Call {
	return &MockAppUpgradedIterator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAppUpgradedIterator_Close_Call) Run(run func()) *MockAppUpgradedIterator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppUpgradedIterator_Close_Call) Return(err error) *MockAppUpgradedIterator_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppUpgradedIterator_Close_Call) RunAndReturn(run func() error) *MockAppUpgradedIterator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockAppUpgradedIterator
func (_mock *MockAppUpgradedIterator) Error() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppUpgradedIterator_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockAppUpgradedIterator_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockAppUpgradedIterator_Expecter) Error() *MockAppUpgradedIterator_Error_Call {
	return &MockAppUpgradedIterator_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockAppUpgradedIterator_Error_Call) Run(run func()) *MockAppUpgradedIterator_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppUpgradedIterator_Error_Call) Return(err error) *MockAppUpgradedIterator_Error_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppUpgradedIterator_Error_Call) RunAndReturn(run func() error) *MockAppUpgradedIterator_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Event provides a mock function for the type MockAppUpgradedIterator
func (_mock *MockAppUpgradedIterator) Event() *AppUpgradedEvent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Event")
	}

	var r0 *AppUpgradedEvent
	if returnFunc, ok := ret.Get(0).(func() *AppUpgradedEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AppUpgradedEvent)
		}
	}
	return r0
}

// MockAppUpgradedIterator_Event_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Event'
type MockAppUpgradedIterator_Event_Call struct {
	*mock.Call
}

// Event is a helper method to define mock.On call
func (_e *MockAppUpgradedIterator_Expecter) Event() *MockAppUpgradedIterator_Event_Call {
	return &MockAppUpgradedIterator_Event_Call{Call: _e.mock.On("Event")}
}

func (_c *MockAppUpgradedIterator_Event_Call) Run(run func()) *MockAppUpgradedIterator_Event_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppUpgradedIterator_Event_Call) Return(appUpgradedEvent *AppUpgradedEvent) *MockAppUpgradedIterator_Event_Call {
	_c.Call.Return(appUpgradedEvent)
	return _c
}

func (_c *MockAppUpgradedIterator_Event_Call) RunAndReturn(run func() *AppUpgradedEvent) *MockAppUpgradedIterator_Event_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockAppUpgradedIterator
func (_mock *MockAppUpgradedIterator) Next() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAppUpgradedIterator_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockAppUpgradedIterator_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockAppUpgradedIterator_Expecter) Next() *MockAppUpgradedIterator_Next_Call {
	return &MockAppUpgradedIterator_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockAppUpgradedIterator_Next_Call) Run(run func()) *MockAppUpgradedIterator_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppUpgradedIterator_Next_Call) Return(b bool) *MockAppUpgradedIterator_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAppUpgradedIterator_Next_Call) RunAndReturn(run func() bool) *MockAppUpgradedIterator_Next_Call {
	_c.Call.Return(run)
	return _c
}
