// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package caller

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppControllerInterface creates a new instance of MockAppControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppControllerInterface {
	mock := &MockAppControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppControllerInterface is an autogenerated mock type for the AppControllerInterface type
type MockAppControllerInterface struct {
	mock.Mock
}

type MockAppControllerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppControllerInterface) EXPECT() *MockAppControllerInterface_Expecter {
	return &MockAppControllerInterface_Expecter{mock: &_m.Mock}
}

// FilterAppUpgraded provides a mock function for the type MockAppControllerInterface
func (_mock *MockAppControllerInterface) FilterAppUpgraded(opts *bind.FilterOpts, apps []common.Address) (AppUpgradedIterator, error) {
	ret := _mock.Called(opts, apps)

	if len(ret) == 0 {
		panic("no return value specified for FilterAppUpgraded")
	}

	var r0 AppUpgradedIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.FilterOpts, []common.Address) (AppUpgradedIterator, error)); ok {
		return returnFunc(opts, apps)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.FilterOpts, []common.Address) AppUpgradedIterator); ok {
		r0 = returnFunc(opts, apps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(AppUpgradedIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.FilterOpts, []common.Address) error); ok {
		r1 = returnFunc(opts, apps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppControllerInterface_FilterAppUpgraded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterAppUpgraded'
type MockAppControllerInterface_FilterAppUpgraded_Call struct {
	*mock.Call
}

// FilterAppUpgraded is a helper method to define mock.On call
//   - opts *bind.FilterOpts
//   - apps []common.Address
func (_e *MockAppControllerInterface_Expecter) FilterAppUpgraded(opts interface{}, apps interface{}) *MockAppControllerInterface_FilterAppUpgraded_Call {
	return &MockAppControllerInterface_FilterAppUpgraded_Call{Call: _e.mock.On("FilterAppUpgraded", opts, apps)}
}

func (_c *MockAppControllerInterface_FilterAppUpgraded_Call) Run(run func(opts *bind.FilterOpts, apps []common.Address)) *MockAppControllerInterface_FilterAppUpgraded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.FilterOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.FilterOpts)
		}
		var arg1 []common.Address
		if args[1] != nil {
			arg1 = args[1].([]common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppControllerInterface_FilterAppUpgraded_Call) Return(appUpgradedIterator AppUpgradedIterator, err error) *MockAppControllerInterface_FilterAppUpgraded_Call {
	_c.Call.Return(appUpgradedIterator, err)
	return _c
}

func (_c *MockAppControllerInterface_FilterAppUpgraded_Call) RunAndReturn(run func(opts *bind.FilterOpts, apps []common.Address) (AppUpgradedIterator, error)) *MockAppControllerInterface_FilterAppUpgraded_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppCreator provides a mock function for the type MockAppControllerInterface
func (_mock *MockAppControllerInterface) GetAppCreator(opts *bind.CallOpts, app common.Address) (common.Address, error) {
	ret := _mock.Called(opts, app)

	if len(ret) == 0 {
		panic("no return value specified for GetAppCreator")
	}

	var r0 common.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (common.Address, error)); ok {
		return returnFunc(opts, app)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) common.Address); ok {
		r0 = returnFunc(opts, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = returnFunc(opts, app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppControllerInterface_GetAppCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppCreator'
type MockAppControllerInterface_GetAppCreator_Call struct {
	*mock.Call
}

// GetAppCreator is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - app common.Address
func (_e *MockAppControllerInterface_Expecter) GetAppCreator(opts interface{}, app interface{}) *MockAppControllerInterface_GetAppCreator_Call {
	return &MockAppControllerInterface_GetAppCreator_Call{Call: _e.mock.On("GetAppCreator", opts, app)}
}

func (_c *MockAppControllerInterface_GetAppCreator_Call) Run(run func(opts *bind.CallOpts, app common.Address)) *MockAppControllerInterface_GetAppCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.CallOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.CallOpts)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppControllerInterface_GetAppCreator_Call) Return(address common.Address, err error) *MockAppControllerInterface_GetAppCreator_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *MockAppControllerInterface_GetAppCreator_Call) RunAndReturn(run func(opts *bind.CallOpts, app common.Address) (common.Address, error)) *MockAppControllerInterface_GetAppCreator_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppLatestReleaseBlockNumber provides a mock function for the type MockAppControllerInterface
func (_mock *MockAppControllerInterface) GetAppLatestReleaseBlockNumber(opts *bind.CallOpts, app common.Address) (uint32, error) {
	ret := _mock.Called(opts, app)

	if len(ret) == 0 {
		panic("no return value specified for GetAppLatestReleaseBlockNumber")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (uint32, error)); ok {
		return returnFunc(opts, app)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) uint32); ok {
		r0 = returnFunc(opts, app)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = returnFunc(opts, app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppLatestReleaseBlockNumber'
type MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call struct {
	*mock.Call
}

// GetAppLatestReleaseBlockNumber is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - app common.Address
func (_e *MockAppControllerInterface_Expecter) GetAppLatestReleaseBlockNumber(opts interface{}, app interface{}) *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call {
	return &MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call{Call: _e.mock.On("GetAppLatestReleaseBlockNumber", opts, app)}
}

func (_c *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call) Run(run func(opts *bind.CallOpts, app common.Address)) *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.CallOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.CallOpts)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call) Return(v uint32, err error) *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call) RunAndReturn(run func(opts *bind.CallOpts, app common.Address) (uint32, error)) *MockAppControllerInterface_GetAppLatestReleaseBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppOperatorSetId provides a mock function for the type MockAppControllerInterface
func (_mock *MockAppControllerInterface) GetAppOperatorSetId(opts *bind.CallOpts, app common.Address) (uint32, error) {
	ret := _mock.Called(opts, app)

	if len(ret) == 0 {
		panic("no return value specified for GetAppOperatorSetId")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (uint32, error)); ok {
		return returnFunc(opts, app)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) uint32); ok {
		r0 = returnFunc(opts, app)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = returnFunc(opts, app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppControllerInterface_GetAppOperatorSetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppOperatorSetId'
type MockAppControllerInterface_GetAppOperatorSetId_Call struct {
	*mock.Call
}

// GetAppOperatorSetId is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - app common.Address
func (_e *MockAppControllerInterface_Expecter) GetAppOperatorSetId(opts interface{}, app interface{}) *MockAppControllerInterface_GetAppOperatorSetId_Call {
	return &MockAppControllerInterface_GetAppOperatorSetId_Call{Call: _e.mock.On("GetAppOperatorSetId", opts, app)}
}

func (_c *MockAppControllerInterface_GetAppOperatorSetId_Call) Run(run func(opts *bind.CallOpts, app common.Address)) *MockAppControllerInterface_GetAppOperatorSetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.CallOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.CallOpts)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppControllerInterface_GetAppOperatorSetId_Call) Return(v uint32, err error) *MockAppControllerInterface_GetAppOperatorSetId_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAppControllerInterface_GetAppOperatorSetId_Call) RunAndReturn(run func(opts *bind.CallOpts, app common.Address) (uint32, error)) *MockAppControllerInterface_GetAppOperatorSetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppStatus provides a mock function for the type MockAppControllerInterface
func (_mock *MockAppControllerInterface) GetAppStatus(opts *bind.CallOpts, app common.Address) (uint8, error) {
	ret := _mock.Called(opts, app)

	if len(ret) == 0 {
		panic("no return value specified for GetAppStatus")
	}

	var r0 uint8
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (uint8, error)); ok {
		return returnFunc(opts, app)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) uint8); ok {
		r0 = returnFunc(opts, app)
	} else {
		r0 = ret.Get(0).(uint8)
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = returnFunc(opts, app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppControllerInterface_GetAppStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppStatus'
type MockAppControllerInterface_GetAppStatus_Call struct {
	*mock.Call
}

// GetAppStatus is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - app common.Address
func (_e *MockAppControllerInterface_Expecter) GetAppStatus(opts interface{}, app interface{}) *MockAppControllerInterface_GetAppStatus_Call {
	return &MockAppControllerInterface_GetAppStatus_Call{Call: _e.mock.On("GetAppStatus", opts, app)}
}

func (_c *MockAppControllerInterface_GetAppStatus_Call) Run(run func(opts *bind.CallOpts, app common.Address)) *MockAppControllerInterface_GetAppStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.CallOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.CallOpts)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppControllerInterface_GetAppStatus_Call) Return(v uint8, err error) *MockAppControllerInterface_GetAppStatus_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAppControllerInterface_GetAppStatus_Call) RunAndReturn(run func(opts *bind.CallOpts, app common.Address) (uint8, error)) *MockAppControllerInterface_GetAppStatus_Call {
	_c.Call.Return(run)
	return _c
}
