// Code generated by mockery v2.42.3. DO NOT EDIT.

package keyGenerator

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIKeyGenerator is an autogenerated mock type for the IKeyGenerator type
type MockIKeyGenerator struct {
	mock.Mock
}

// GenerateECDSAKey provides a mock function with given fields: ctx, keyName, aliasName
func (_m *MockIKeyGenerator) GenerateECDSAKey(ctx context.Context, keyName string, aliasName string) (*GeneratedECDSAKey, error) {
	ret := _m.Called(ctx, keyName, aliasName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateECDSAKey")
	}

	var r0 *GeneratedECDSAKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*GeneratedECDSAKey, error)); ok {
		return rf(ctx, keyName, aliasName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *GeneratedECDSAKey); ok {
		r0 = rf(ctx, keyName, aliasName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GeneratedECDSAKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, keyName, aliasName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetECDSAKeyById provides a mock function with given fields: ctx, keyId
func (_m *MockIKeyGenerator) GetECDSAKeyById(ctx context.Context, keyId string) (*GeneratedECDSAKey, error) {
	ret := _m.Called(ctx, keyId)

	if len(ret) == 0 {
		panic("no return value specified for GetECDSAKeyById")
	}

	var r0 *GeneratedECDSAKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*GeneratedECDSAKey, error)); ok {
		return rf(ctx, keyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *GeneratedECDSAKey); ok {
		r0 = rf(ctx, keyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GeneratedECDSAKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignMessage provides a mock function with given fields: ctx, keyId, message
func (_m *MockIKeyGenerator) SignMessage(ctx context.Context, keyId string, message []byte) ([]byte, error) {
	ret := _m.Called(ctx, keyId, message)

	if len(ret) == 0 {
		panic("no return value specified for SignMessage")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return rf(ctx, keyId, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = rf(ctx, keyId, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, keyId, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIKeyGenerator creates a new instance of MockIKeyGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIKeyGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIKeyGenerator {
	mock := &MockIKeyGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
