// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package keyGenerator

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIKeyGenerator creates a new instance of MockIKeyGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIKeyGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIKeyGenerator {
	mock := &MockIKeyGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIKeyGenerator is an autogenerated mock type for the IKeyGenerator type
type MockIKeyGenerator struct {
	mock.Mock
}

type MockIKeyGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIKeyGenerator) EXPECT() *MockIKeyGenerator_Expecter {
	return &MockIKeyGenerator_Expecter{mock: &_m.Mock}
}

// GenerateECDSAKey provides a mock function for the type MockIKeyGenerator
func (_mock *MockIKeyGenerator) GenerateECDSAKey(ctx context.Context, keyName string, aliasName string) (*GeneratedECDSAKey, error) {
	ret := _mock.Called(ctx, keyName, aliasName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateECDSAKey")
	}

	var r0 *GeneratedECDSAKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*GeneratedECDSAKey, error)); ok {
		return returnFunc(ctx, keyName, aliasName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *GeneratedECDSAKey); ok {
		r0 = returnFunc(ctx, keyName, aliasName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GeneratedECDSAKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, keyName, aliasName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKeyGenerator_GenerateECDSAKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateECDSAKey'
type MockIKeyGenerator_GenerateECDSAKey_Call struct {
	*mock.Call
}

// GenerateECDSAKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyName string
//   - aliasName string
func (_e *MockIKeyGenerator_Expecter) GenerateECDSAKey(ctx interface{}, keyName interface{}, aliasName interface{}) *MockIKeyGenerator_GenerateECDSAKey_Call {
	return &MockIKeyGenerator_GenerateECDSAKey_Call{Call: _e.mock.On("GenerateECDSAKey", ctx, keyName, aliasName)}
}

func (_c *MockIKeyGenerator_GenerateECDSAKey_Call) Run(run func(ctx context.Context, keyName string, aliasName string)) *MockIKeyGenerator_GenerateECDSAKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKeyGenerator_GenerateECDSAKey_Call) Return(generatedECDSAKey *GeneratedECDSAKey, err error) *MockIKeyGenerator_GenerateECDSAKey_Call {
	_c.Call.Return(generatedECDSAKey, err)
	return _c
}

func (_c *MockIKeyGenerator_GenerateECDSAKey_Call) RunAndReturn(run func(ctx context.Context, keyName string, aliasName string) (*GeneratedECDSAKey, error)) *MockIKeyGenerator_GenerateECDSAKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetECDSAKeyById provides a mock function for the type MockIKeyGenerator
func (_mock *MockIKeyGenerator) GetECDSAKeyById(ctx context.Context, keyId string) (*GeneratedECDSAKey, error) {
	ret := _mock.Called(ctx, keyId)

	if len(ret) == 0 {
		panic("no return value specified for GetECDSAKeyById")
	}

	var r0 *GeneratedECDSAKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*GeneratedECDSAKey, error)); ok {
		return returnFunc(ctx, keyId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *GeneratedECDSAKey); ok {
		r0 = returnFunc(ctx, keyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GeneratedECDSAKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKeyGenerator_GetECDSAKeyById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetECDSAKeyById'
type MockIKeyGenerator_GetECDSAKeyById_Call struct {
	*mock.Call
}

// GetECDSAKeyById is a helper method to define mock.On call
//   - ctx context.Context
//   - keyId string
func (_e *MockIKeyGenerator_Expecter) GetECDSAKeyById(ctx interface{}, keyId interface{}) *MockIKeyGenerator_GetECDSAKeyById_Call {
	return &MockIKeyGenerator_GetECDSAKeyById_Call{Call: _e.mock.On("GetECDSAKeyById", ctx, keyId)}
}

func (_c *MockIKeyGenerator_GetECDSAKeyById_Call) Run(run func(ctx context.Context, keyId string)) *MockIKeyGenerator_GetECDSAKeyById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIKeyGenerator_GetECDSAKeyById_Call) Return(generatedECDSAKey *GeneratedECDSAKey, err error) *MockIKeyGenerator_GetECDSAKeyById_Call {
	_c.Call.Return(generatedECDSAKey, err)
	return _c
}

func (_c *MockIKeyGenerator_GetECDSAKeyById_Call) RunAndReturn(run func(ctx context.Context, keyId string) (*GeneratedECDSAKey, error)) *MockIKeyGenerator_GetECDSAKeyById_Call {
	_c.Call.Return(run)
	return _c
}

// SignMessage provides a mock function for the type MockIKeyGenerator
func (_mock *MockIKeyGenerator) SignMessage(ctx context.Context, keyId string, message []byte) ([]byte, error) {
	ret := _mock.Called(ctx, keyId, message)

	if len(ret) == 0 {
		panic("no return value specified for SignMessage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, keyId, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = returnFunc(ctx, keyId, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, keyId, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKeyGenerator_SignMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignMessage'
type MockIKeyGenerator_SignMessage_Call struct {
	*mock.Call
}

// SignMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - keyId string
//   - message []byte
func (_e *MockIKeyGenerator_Expecter) SignMessage(ctx interface{}, keyId interface{}, message interface{}) *MockIKeyGenerator_SignMessage_Call {
	return &MockIKeyGenerator_SignMessage_Call{Call: _e.mock.On("SignMessage", ctx, keyId, message)}
}

func (_c *MockIKeyGenerator_SignMessage_Call) Run(run func(ctx context.Context, keyId string, message []byte)) *MockIKeyGenerator_SignMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKeyGenerator_SignMessage_Call) Return(bytes []byte, err error) *MockIKeyGenerator_SignMessage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIKeyGenerator_SignMessage_Call) RunAndReturn(run func(ctx context.Context, keyId string, message []byte) ([]byte, error)) *MockIKeyGenerator_SignMessage_Call {
	_c.Call.Return(run)
	return _c
}
