// Code generated by mockery v2.42.3. DO NOT EDIT.

package web3signer

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockIWeb3Signer is an autogenerated mock type for the IWeb3Signer type
type MockIWeb3Signer struct {
	mock.Mock
}

// EthAccounts provides a mock function with given fields: ctx
func (_m *MockIWeb3Signer) EthAccounts(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EthAccounts")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthSign provides a mock function with given fields: ctx, account, data
func (_m *MockIWeb3Signer) EthSign(ctx context.Context, account string, data string) (string, error) {
	ret := _m.Called(ctx, account, data)

	if len(ret) == 0 {
		panic("no return value specified for EthSign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, account, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, account, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, account, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthSignTransaction provides a mock function with given fields: ctx, from, transaction
func (_m *MockIWeb3Signer) EthSignTransaction(ctx context.Context, from string, transaction map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, from, transaction)

	if len(ret) == 0 {
		panic("no return value specified for EthSignTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (string, error)); ok {
		return rf(ctx, from, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, from, transaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, from, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthSignTypedData provides a mock function with given fields: ctx, account, typedData
func (_m *MockIWeb3Signer) EthSignTypedData(ctx context.Context, account string, typedData interface{}) (string, error) {
	ret := _m.Called(ctx, account, typedData)

	if len(ret) == 0 {
		panic("no return value specified for EthSignTypedData")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (string, error)); ok {
		return rf(ctx, account, typedData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) string); ok {
		r0 = rf(ctx, account, typedData)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, account, typedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPublicKeys provides a mock function with given fields: ctx
func (_m *MockIWeb3Signer) ListPublicKeys(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicKeys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReloadKeys provides a mock function with given fields: ctx
func (_m *MockIWeb3Signer) ReloadKeys(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReloadKeysAndWaitForPublicKey provides a mock function with given fields: ctx, publicKey
func (_m *MockIWeb3Signer) ReloadKeysAndWaitForPublicKey(ctx context.Context, publicKey string) error {
	ret := _m.Called(ctx, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for ReloadKeysAndWaitForPublicKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, publicKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetHttpClient provides a mock function with given fields: client
func (_m *MockIWeb3Signer) SetHttpClient(client *http.Client) {
	_m.Called(client)
}

// Sign provides a mock function with given fields: ctx, account, data
func (_m *MockIWeb3Signer) Sign(ctx context.Context, account string, data string) (string, error) {
	ret := _m.Called(ctx, account, data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, account, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, account, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, account, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignRaw provides a mock function with given fields: ctx, identifier, data
func (_m *MockIWeb3Signer) SignRaw(ctx context.Context, identifier string, data []byte) (string, error) {
	ret := _m.Called(ctx, identifier, data)

	if len(ret) == 0 {
		panic("no return value specified for SignRaw")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, identifier, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, identifier, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, identifier, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIWeb3Signer creates a new instance of MockIWeb3Signer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWeb3Signer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWeb3Signer {
	mock := &MockIWeb3Signer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
