// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package web3signer

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIWeb3Signer creates a new instance of MockIWeb3Signer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWeb3Signer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWeb3Signer {
	mock := &MockIWeb3Signer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIWeb3Signer is an autogenerated mock type for the IWeb3Signer type
type MockIWeb3Signer struct {
	mock.Mock
}

type MockIWeb3Signer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWeb3Signer) EXPECT() *MockIWeb3Signer_Expecter {
	return &MockIWeb3Signer_Expecter{mock: &_m.Mock}
}

// EthAccounts provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) EthAccounts(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EthAccounts")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_EthAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EthAccounts'
type MockIWeb3Signer_EthAccounts_Call struct {
	*mock.Call
}

// EthAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIWeb3Signer_Expecter) EthAccounts(ctx interface{}) *MockIWeb3Signer_EthAccounts_Call {
	return &MockIWeb3Signer_EthAccounts_Call{Call: _e.mock.On("EthAccounts", ctx)}
}

func (_c *MockIWeb3Signer_EthAccounts_Call) Run(run func(ctx context.Context)) *MockIWeb3Signer_EthAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_EthAccounts_Call) Return(strings []string, err error) *MockIWeb3Signer_EthAccounts_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIWeb3Signer_EthAccounts_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockIWeb3Signer_EthAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// EthSign provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) EthSign(ctx context.Context, account string, data string) (string, error) {
	ret := _mock.Called(ctx, account, data)

	if len(ret) == 0 {
		panic("no return value specified for EthSign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, account, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, account, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, account, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_EthSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EthSign'
type MockIWeb3Signer_EthSign_Call struct {
	*mock.Call
}

// EthSign is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - data string
func (_e *MockIWeb3Signer_Expecter) EthSign(ctx interface{}, account interface{}, data interface{}) *MockIWeb3Signer_EthSign_Call {
	return &MockIWeb3Signer_EthSign_Call{Call: _e.mock.On("EthSign", ctx, account, data)}
}

func (_c *MockIWeb3Signer_EthSign_Call) Run(run func(ctx context.Context, account string, data string)) *MockIWeb3Signer_EthSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_EthSign_Call) Return(s string, err error) *MockIWeb3Signer_EthSign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIWeb3Signer_EthSign_Call) RunAndReturn(run func(ctx context.Context, account string, data string) (string, error)) *MockIWeb3Signer_EthSign_Call {
	_c.Call.Return(run)
	return _c
}

// EthSignTransaction provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) EthSignTransaction(ctx context.Context, from string, transaction map[string]interface{}) (string, error) {
	ret := _mock.Called(ctx, from, transaction)

	if len(ret) == 0 {
		panic("no return value specified for EthSignTransaction")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (string, error)); ok {
		return returnFunc(ctx, from, transaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) string); ok {
		r0 = returnFunc(ctx, from, transaction)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, from, transaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_EthSignTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EthSignTransaction'
type MockIWeb3Signer_EthSignTransaction_Call struct {
	*mock.Call
}

// EthSignTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - transaction map[string]interface{}
func (_e *MockIWeb3Signer_Expecter) EthSignTransaction(ctx interface{}, from interface{}, transaction interface{}) *MockIWeb3Signer_EthSignTransaction_Call {
	return &MockIWeb3Signer_EthSignTransaction_Call{Call: _e.mock.On("EthSignTransaction", ctx, from, transaction)}
}

func (_c *MockIWeb3Signer_EthSignTransaction_Call) Run(run func(ctx context.Context, from string, transaction map[string]interface{})) *MockIWeb3Signer_EthSignTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_EthSignTransaction_Call) Return(s string, err error) *MockIWeb3Signer_EthSignTransaction_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIWeb3Signer_EthSignTransaction_Call) RunAndReturn(run func(ctx context.Context, from string, transaction map[string]interface{}) (string, error)) *MockIWeb3Signer_EthSignTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// EthSignTypedData provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) EthSignTypedData(ctx context.Context, account string, typedData interface{}) (string, error) {
	ret := _mock.Called(ctx, account, typedData)

	if len(ret) == 0 {
		panic("no return value specified for EthSignTypedData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) (string, error)); ok {
		return returnFunc(ctx, account, typedData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) string); ok {
		r0 = returnFunc(ctx, account, typedData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = returnFunc(ctx, account, typedData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_EthSignTypedData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EthSignTypedData'
type MockIWeb3Signer_EthSignTypedData_Call struct {
	*mock.Call
}

// EthSignTypedData is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - typedData interface{}
func (_e *MockIWeb3Signer_Expecter) EthSignTypedData(ctx interface{}, account interface{}, typedData interface{}) *MockIWeb3Signer_EthSignTypedData_Call {
	return &MockIWeb3Signer_EthSignTypedData_Call{Call: _e.mock.On("EthSignTypedData", ctx, account, typedData)}
}

func (_c *MockIWeb3Signer_EthSignTypedData_Call) Run(run func(ctx context.Context, account string, typedData interface{})) *MockIWeb3Signer_EthSignTypedData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_EthSignTypedData_Call) Return(s string, err error) *MockIWeb3Signer_EthSignTypedData_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIWeb3Signer_EthSignTypedData_Call) RunAndReturn(run func(ctx context.Context, account string, typedData interface{}) (string, error)) *MockIWeb3Signer_EthSignTypedData_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicKeys provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) ListPublicKeys(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_ListPublicKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicKeys'
type MockIWeb3Signer_ListPublicKeys_Call struct {
	*mock.Call
}

// ListPublicKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIWeb3Signer_Expecter) ListPublicKeys(ctx interface{}) *MockIWeb3Signer_ListPublicKeys_Call {
	return &MockIWeb3Signer_ListPublicKeys_Call{Call: _e.mock.On("ListPublicKeys", ctx)}
}

func (_c *MockIWeb3Signer_ListPublicKeys_Call) Run(run func(ctx context.Context)) *MockIWeb3Signer_ListPublicKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_ListPublicKeys_Call) Return(strings []string, err error) *MockIWeb3Signer_ListPublicKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIWeb3Signer_ListPublicKeys_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockIWeb3Signer_ListPublicKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadKeys provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) ReloadKeys(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIWeb3Signer_ReloadKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadKeys'
type MockIWeb3Signer_ReloadKeys_Call struct {
	*mock.Call
}

// ReloadKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIWeb3Signer_Expecter) ReloadKeys(ctx interface{}) *MockIWeb3Signer_ReloadKeys_Call {
	return &MockIWeb3Signer_ReloadKeys_Call{Call: _e.mock.On("ReloadKeys", ctx)}
}

func (_c *MockIWeb3Signer_ReloadKeys_Call) Run(run func(ctx context.Context)) *MockIWeb3Signer_ReloadKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_ReloadKeys_Call) Return(err error) *MockIWeb3Signer_ReloadKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIWeb3Signer_ReloadKeys_Call) RunAndReturn(run func(ctx context.Context) error) *MockIWeb3Signer_ReloadKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadKeysAndWaitForPublicKey provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) ReloadKeysAndWaitForPublicKey(ctx context.Context, publicKey string) error {
	ret := _mock.Called(ctx, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for ReloadKeysAndWaitForPublicKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, publicKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadKeysAndWaitForPublicKey'
type MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call struct {
	*mock.Call
}

// ReloadKeysAndWaitForPublicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - publicKey string
func (_e *MockIWeb3Signer_Expecter) ReloadKeysAndWaitForPublicKey(ctx interface{}, publicKey interface{}) *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call {
	return &MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call{Call: _e.mock.On("ReloadKeysAndWaitForPublicKey", ctx, publicKey)}
}

func (_c *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call) Run(run func(ctx context.Context, publicKey string)) *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call) Return(err error) *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call) RunAndReturn(run func(ctx context.Context, publicKey string) error) *MockIWeb3Signer_ReloadKeysAndWaitForPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetHttpClient provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) SetHttpClient(client *http.Client) {
	_mock.Called(client)
	return
}

// MockIWeb3Signer_SetHttpClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHttpClient'
type MockIWeb3Signer_SetHttpClient_Call struct {
	*mock.Call
}

// SetHttpClient is a helper method to define mock.On call
//   - client *http.Client
func (_e *MockIWeb3Signer_Expecter) SetHttpClient(client interface{}) *MockIWeb3Signer_SetHttpClient_Call {
	return &MockIWeb3Signer_SetHttpClient_Call{Call: _e.mock.On("SetHttpClient", client)}
}

func (_c *MockIWeb3Signer_SetHttpClient_Call) Run(run func(client *http.Client)) *MockIWeb3Signer_SetHttpClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Client
		if args[0] != nil {
			arg0 = args[0].(*http.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_SetHttpClient_Call) Return() *MockIWeb3Signer_SetHttpClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIWeb3Signer_SetHttpClient_Call) RunAndReturn(run func(client *http.Client)) *MockIWeb3Signer_SetHttpClient_Call {
	_c.Run(run)
	return _c
}

// Sign provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) Sign(ctx context.Context, account string, data string) (string, error) {
	ret := _mock.Called(ctx, account, data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, account, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, account, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, account, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockIWeb3Signer_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - data string
func (_e *MockIWeb3Signer_Expecter) Sign(ctx interface{}, account interface{}, data interface{}) *MockIWeb3Signer_Sign_Call {
	return &MockIWeb3Signer_Sign_Call{Call: _e.mock.On("Sign", ctx, account, data)}
}

func (_c *MockIWeb3Signer_Sign_Call) Run(run func(ctx context.Context, account string, data string)) *MockIWeb3Signer_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_Sign_Call) Return(s string, err error) *MockIWeb3Signer_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIWeb3Signer_Sign_Call) RunAndReturn(run func(ctx context.Context, account string, data string) (string, error)) *MockIWeb3Signer_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignRaw provides a mock function for the type MockIWeb3Signer
func (_mock *MockIWeb3Signer) SignRaw(ctx context.Context, identifier string, data []byte) (string, error) {
	ret := _mock.Called(ctx, identifier, data)

	if len(ret) == 0 {
		panic("no return value specified for SignRaw")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return returnFunc(ctx, identifier, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = returnFunc(ctx, identifier, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, identifier, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIWeb3Signer_SignRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignRaw'
type MockIWeb3Signer_SignRaw_Call struct {
	*mock.Call
}

// SignRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - data []byte
func (_e *MockIWeb3Signer_Expecter) SignRaw(ctx interface{}, identifier interface{}, data interface{}) *MockIWeb3Signer_SignRaw_Call {
	return &MockIWeb3Signer_SignRaw_Call{Call: _e.mock.On("SignRaw", ctx, identifier, data)}
}

func (_c *MockIWeb3Signer_SignRaw_Call) Run(run func(ctx context.Context, identifier string, data []byte)) *MockIWeb3Signer_SignRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIWeb3Signer_SignRaw_Call) Return(s string, err error) *MockIWeb3Signer_SignRaw_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIWeb3Signer_SignRaw_Call) RunAndReturn(run func(ctx context.Context, identifier string, data []byte) (string, error)) *MockIWeb3Signer_SignRaw_Call {
	_c.Call.Return(run)
	return _c
}
