// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package contractCaller

import (
	"github.com/Layr-Labs/eigenx-kms-go/pkg/peering"
	"github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIContractCaller creates a new instance of MockIContractCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIContractCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIContractCaller {
	mock := &MockIContractCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIContractCaller is an autogenerated mock type for the IContractCaller type
type MockIContractCaller struct {
	mock.Mock
}

type MockIContractCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIContractCaller) EXPECT() *MockIContractCaller_Expecter {
	return &MockIContractCaller_Expecter{mock: &_m.Mock}
}

// GetOperatorSetDetailsForOperator provides a mock function for the type MockIContractCaller
func (_mock *MockIContractCaller) GetOperatorSetDetailsForOperator(operatorAddress common.Address, avsAddress string, operatorSetId uint32) (*peering.OperatorSetPeer, error) {
	ret := _mock.Called(operatorAddress, avsAddress, operatorSetId)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSetDetailsForOperator")
	}

	var r0 *peering.OperatorSetPeer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(common.Address, string, uint32) (*peering.OperatorSetPeer, error)); ok {
		return returnFunc(operatorAddress, avsAddress, operatorSetId)
	}
	if returnFunc, ok := ret.Get(0).(func(common.Address, string, uint32) *peering.OperatorSetPeer); ok {
		r0 = returnFunc(operatorAddress, avsAddress, operatorSetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peering.OperatorSetPeer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(common.Address, string, uint32) error); ok {
		r1 = returnFunc(operatorAddress, avsAddress, operatorSetId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIContractCaller_GetOperatorSetDetailsForOperator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorSetDetailsForOperator'
type MockIContractCaller_GetOperatorSetDetailsForOperator_Call struct {
	*mock.Call
}

// GetOperatorSetDetailsForOperator is a helper method to define mock.On call
//   - operatorAddress common.Address
//   - avsAddress string
//   - operatorSetId uint32
func (_e *MockIContractCaller_Expecter) GetOperatorSetDetailsForOperator(operatorAddress interface{}, avsAddress interface{}, operatorSetId interface{}) *MockIContractCaller_GetOperatorSetDetailsForOperator_Call {
	return &MockIContractCaller_GetOperatorSetDetailsForOperator_Call{Call: _e.mock.On("GetOperatorSetDetailsForOperator", operatorAddress, avsAddress, operatorSetId)}
}

func (_c *MockIContractCaller_GetOperatorSetDetailsForOperator_Call) Run(run func(operatorAddress common.Address, avsAddress string, operatorSetId uint32)) *MockIContractCaller_GetOperatorSetDetailsForOperator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.Address
		if args[0] != nil {
			arg0 = args[0].(common.Address)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetDetailsForOperator_Call) Return(operatorSetPeer *peering.OperatorSetPeer, err error) *MockIContractCaller_GetOperatorSetDetailsForOperator_Call {
	_c.Call.Return(operatorSetPeer, err)
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetDetailsForOperator_Call) RunAndReturn(run func(operatorAddress common.Address, avsAddress string, operatorSetId uint32) (*peering.OperatorSetPeer, error)) *MockIContractCaller_GetOperatorSetDetailsForOperator_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperatorSetMembers provides a mock function for the type MockIContractCaller
func (_mock *MockIContractCaller) GetOperatorSetMembers(avsAddress string, operatorSetId uint32) ([]string, error) {
	ret := _mock.Called(avsAddress, operatorSetId)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSetMembers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint32) ([]string, error)); ok {
		return returnFunc(avsAddress, operatorSetId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint32) []string); ok {
		r0 = returnFunc(avsAddress, operatorSetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint32) error); ok {
		r1 = returnFunc(avsAddress, operatorSetId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIContractCaller_GetOperatorSetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorSetMembers'
type MockIContractCaller_GetOperatorSetMembers_Call struct {
	*mock.Call
}

// GetOperatorSetMembers is a helper method to define mock.On call
//   - avsAddress string
//   - operatorSetId uint32
func (_e *MockIContractCaller_Expecter) GetOperatorSetMembers(avsAddress interface{}, operatorSetId interface{}) *MockIContractCaller_GetOperatorSetMembers_Call {
	return &MockIContractCaller_GetOperatorSetMembers_Call{Call: _e.mock.On("GetOperatorSetMembers", avsAddress, operatorSetId)}
}

func (_c *MockIContractCaller_GetOperatorSetMembers_Call) Run(run func(avsAddress string, operatorSetId uint32)) *MockIContractCaller_GetOperatorSetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetMembers_Call) Return(strings []string, err error) *MockIContractCaller_GetOperatorSetMembers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetMembers_Call) RunAndReturn(run func(avsAddress string, operatorSetId uint32) ([]string, error)) *MockIContractCaller_GetOperatorSetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperatorSetMembersWithPeering provides a mock function for the type MockIContractCaller
func (_mock *MockIContractCaller) GetOperatorSetMembersWithPeering(avsAddress string, operatorSetId uint32) (*peering.OperatorSetPeers, error) {
	ret := _mock.Called(avsAddress, operatorSetId)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSetMembersWithPeering")
	}

	var r0 *peering.OperatorSetPeers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint32) (*peering.OperatorSetPeers, error)); ok {
		return returnFunc(avsAddress, operatorSetId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint32) *peering.OperatorSetPeers); ok {
		r0 = returnFunc(avsAddress, operatorSetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peering.OperatorSetPeers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint32) error); ok {
		r1 = returnFunc(avsAddress, operatorSetId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIContractCaller_GetOperatorSetMembersWithPeering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorSetMembersWithPeering'
type MockIContractCaller_GetOperatorSetMembersWithPeering_Call struct {
	*mock.Call
}

// GetOperatorSetMembersWithPeering is a helper method to define mock.On call
//   - avsAddress string
//   - operatorSetId uint32
func (_e *MockIContractCaller_Expecter) GetOperatorSetMembersWithPeering(avsAddress interface{}, operatorSetId interface{}) *MockIContractCaller_GetOperatorSetMembersWithPeering_Call {
	return &MockIContractCaller_GetOperatorSetMembersWithPeering_Call{Call: _e.mock.On("GetOperatorSetMembersWithPeering", avsAddress, operatorSetId)}
}

func (_c *MockIContractCaller_GetOperatorSetMembersWithPeering_Call) Run(run func(avsAddress string, operatorSetId uint32)) *MockIContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetMembersWithPeering_Call) Return(operatorSetPeers *peering.OperatorSetPeers, err error) *MockIContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Return(operatorSetPeers, err)
	return _c
}

func (_c *MockIContractCaller_GetOperatorSetMembersWithPeering_Call) RunAndReturn(run func(avsAddress string, operatorSetId uint32) (*peering.OperatorSetPeers, error)) *MockIContractCaller_GetOperatorSetMembersWithPeering_Call {
	_c.Call.Return(run)
	return _c
}
